// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countProducts = `-- name: CountProducts :one
SELECT count(*) FROM products
WHERE organization_id = $1
  AND ($2::uuid IS NULL OR category_id = $2)
`

type CountProductsParams struct {
	OrganizationID uuid.UUID
	CategoryID     uuid.NullUUID
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, arg.OrganizationID, arg.CategoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublicProducts = `-- name: CountPublicProducts :one
SELECT count(DISTINCT p.id)
FROM products p
JOIN organizations o ON o.id = p.organization_id
LEFT JOIN categories c ON c.id = p.category_id
JOIN product_variants v ON v.product_id = p.id AND v.is_active
WHERE o.status = 'active' AND p.is_active AND 'ecommerce' = ANY(p.channels)
  AND ($1::uuid IS NULL OR p.organization_id = $1)
  AND ($2::text IS NULL OR o.slug = $2)
  AND ($3::text IS NULL OR p.name ILIKE '%' || $3::text || '%')
  AND ($4::text IS NULL OR c.name ILIKE $4::text)
`

type CountPublicProductsParams struct {
	OrganizationID   uuid.NullUUID
	OrganizationSlug *string
	Search           *string
	Category         *string
}

// Mismos JOIN y filtros que ListPublicProducts — tiene que coincidir siempre con esa consulta.
func (q *Queries) CountPublicProducts(ctx context.Context, arg CountPublicProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicProducts,
		arg.OrganizationID,
		arg.OrganizationSlug,
		arg.Search,
		arg.Category,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deactivateOtherModifierOptions = `-- name: DeactivateOtherModifierOptions :exec
UPDATE modifier_options
SET is_active = false, updated_at = now()
WHERE modifier_group_id = $1 AND organization_id = $2
  AND NOT (id = ANY($3::uuid[]))
`

type DeactivateOtherModifierOptionsParams struct {
	ModifierGroupID uuid.UUID
	OrganizationID  uuid.UUID
	KeepIds         []uuid.UUID
}

func (q *Queries) DeactivateOtherModifierOptions(ctx context.Context, arg DeactivateOtherModifierOptionsParams) error {
	_, err := q.db.Exec(ctx, deactivateOtherModifierOptions, arg.ModifierGroupID, arg.OrganizationID, arg.KeepIds)
	return err
}

const deactivateOtherVariants = `-- name: DeactivateOtherVariants :exec
UPDATE product_variants
SET is_active = false, updated_at = now()
WHERE product_id = $1 AND organization_id = $2
  AND NOT (id = ANY($3::uuid[]))
`

type DeactivateOtherVariantsParams struct {
	ProductID      uuid.UUID
	OrganizationID uuid.UUID
	KeepIds        []uuid.UUID
}

// Todas las que no vinieron en el reemplazo, de un solo golpe.
func (q *Queries) DeactivateOtherVariants(ctx context.Context, arg DeactivateOtherVariantsParams) error {
	_, err := q.db.Exec(ctx, deactivateOtherVariants, arg.ProductID, arg.OrganizationID, arg.KeepIds)
	return err
}

const deleteProductModifierGroups = `-- name: DeleteProductModifierGroups :exec
DELETE FROM product_modifier_groups WHERE product_id = $1 AND organization_id = $2
`

type DeleteProductModifierGroupsParams struct {
	ProductID      uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) DeleteProductModifierGroups(ctx context.Context, arg DeleteProductModifierGroupsParams) error {
	_, err := q.db.Exec(ctx, deleteProductModifierGroups, arg.ProductID, arg.OrganizationID)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, organization_id, name, position, is_active, created_at, updated_at FROM categories WHERE id = $1 AND organization_id = $2
`

type GetCategoryParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.OrganizationID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Position,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModifierGroup = `-- name: GetModifierGroup :one
SELECT id, organization_id, name, selection_type, min_select, max_select, is_active, created_at, updated_at FROM modifier_groups WHERE id = $1 AND organization_id = $2
`

type GetModifierGroupParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) GetModifierGroup(ctx context.Context, arg GetModifierGroupParams) (ModifierGroup, error) {
	row := q.db.QueryRow(ctx, getModifierGroup, arg.ID, arg.OrganizationID)
	var i ModifierGroup
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.SelectionType,
		&i.MinSelect,
		&i.MaxSelect,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModifierGroupsByIDs = `-- name: GetModifierGroupsByIDs :many
SELECT id, organization_id, name, selection_type, min_select, max_select, is_active, created_at, updated_at FROM modifier_groups WHERE id = ANY($1::uuid[]) AND organization_id = $2
`

type GetModifierGroupsByIDsParams struct {
	Ids            []uuid.UUID
	OrganizationID uuid.UUID
}

// Usada por internal/orders (a través de catalog.Repository) para armar la línea de un pedido:
// necesita TODOS los grupos que aplican a un producto para validar obligatoriedad y min/max,
// no solo los que el cliente eligió.
func (q *Queries) GetModifierGroupsByIDs(ctx context.Context, arg GetModifierGroupsByIDsParams) ([]ModifierGroup, error) {
	rows, err := q.db.Query(ctx, getModifierGroupsByIDs, arg.Ids, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModifierGroup{}
	for rows.Next() {
		var i ModifierGroup
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.SelectionType,
			&i.MinSelect,
			&i.MaxSelect,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProduct = `-- name: GetProduct :one
SELECT id, organization_id, category_id, name, description, image_url, position, is_active, created_at, updated_at, ingredients, channels, promo_discount_bps FROM products WHERE id = $1 AND organization_id = $2
`

type GetProductParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) GetProduct(ctx context.Context, arg GetProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, arg.ID, arg.OrganizationID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.Position,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Ingredients,
		&i.Channels,
		&i.PromoDiscountBps,
	)
	return i, err
}

const insertCategory = `-- name: InsertCategory :one

INSERT INTO categories (organization_id, name, position)
VALUES ($1, $2, $3)
RETURNING id, organization_id, name, position, is_active, created_at, updated_at
`

type InsertCategoryParams struct {
	OrganizationID uuid.UUID
	Name           string
	Position       int32
}

// ---------------------------------------------------------------------------
// Categorías
// ---------------------------------------------------------------------------
func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, insertCategory, arg.OrganizationID, arg.Name, arg.Position)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Position,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertModifierGroup = `-- name: InsertModifierGroup :one

INSERT INTO modifier_groups (organization_id, name, selection_type, min_select, max_select)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, name, selection_type, min_select, max_select, is_active, created_at, updated_at
`

type InsertModifierGroupParams struct {
	OrganizationID uuid.UUID
	Name           string
	SelectionType  string
	MinSelect      int32
	MaxSelect      int32
}

// ---------------------------------------------------------------------------
// Grupos de modificadores
// ---------------------------------------------------------------------------
func (q *Queries) InsertModifierGroup(ctx context.Context, arg InsertModifierGroupParams) (ModifierGroup, error) {
	row := q.db.QueryRow(ctx, insertModifierGroup,
		arg.OrganizationID,
		arg.Name,
		arg.SelectionType,
		arg.MinSelect,
		arg.MaxSelect,
	)
	var i ModifierGroup
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.SelectionType,
		&i.MinSelect,
		&i.MaxSelect,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertModifierOption = `-- name: InsertModifierOption :one
INSERT INTO modifier_options (modifier_group_id, organization_id, name, price_delta_cents, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, modifier_group_id, organization_id, name, price_delta_cents, is_active, position, created_at, updated_at
`

type InsertModifierOptionParams struct {
	ModifierGroupID uuid.UUID
	OrganizationID  uuid.UUID
	Name            string
	PriceDeltaCents int32
	Position        int32
}

func (q *Queries) InsertModifierOption(ctx context.Context, arg InsertModifierOptionParams) (ModifierOption, error) {
	row := q.db.QueryRow(ctx, insertModifierOption,
		arg.ModifierGroupID,
		arg.OrganizationID,
		arg.Name,
		arg.PriceDeltaCents,
		arg.Position,
	)
	var i ModifierOption
	err := row.Scan(
		&i.ID,
		&i.ModifierGroupID,
		&i.OrganizationID,
		&i.Name,
		&i.PriceDeltaCents,
		&i.IsActive,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProduct = `-- name: InsertProduct :one

INSERT INTO products (organization_id, category_id, name, description, image_url, position, ingredients, channels,
                      promo_discount_bps)
VALUES ($1, $2, $3, $4, $5, $6,
        $7::text[], $8::text[], $9)
RETURNING id, organization_id, category_id, name, description, image_url, position, is_active, created_at, updated_at, ingredients, channels, promo_discount_bps
`

type InsertProductParams struct {
	OrganizationID   uuid.UUID
	CategoryID       uuid.NullUUID
	Name             string
	Description      *string
	ImageUrl         *string
	Position         int32
	Ingredients      []string
	Channels         []string
	PromoDiscountBps int32
}

// ---------------------------------------------------------------------------
// Productos
// ---------------------------------------------------------------------------
func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, insertProduct,
		arg.OrganizationID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
		arg.Position,
		arg.Ingredients,
		arg.Channels,
		arg.PromoDiscountBps,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.Position,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Ingredients,
		&i.Channels,
		&i.PromoDiscountBps,
	)
	return i, err
}

const insertProductModifierGroup = `-- name: InsertProductModifierGroup :exec
INSERT INTO product_modifier_groups (product_id, organization_id, modifier_group_id, position)
VALUES ($1, $2, $3, $4)
`

type InsertProductModifierGroupParams struct {
	ProductID       uuid.UUID
	OrganizationID  uuid.UUID
	ModifierGroupID uuid.UUID
	Position        int32
}

func (q *Queries) InsertProductModifierGroup(ctx context.Context, arg InsertProductModifierGroupParams) error {
	_, err := q.db.Exec(ctx, insertProductModifierGroup,
		arg.ProductID,
		arg.OrganizationID,
		arg.ModifierGroupID,
		arg.Position,
	)
	return err
}

const insertVariant = `-- name: InsertVariant :one
INSERT INTO product_variants (product_id, organization_id, name, price_cents, is_default, position)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, product_id, organization_id, name, price_cents, is_default, is_active, position, created_at, updated_at
`

type InsertVariantParams struct {
	ProductID      uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	PriceCents     int32
	IsDefault      bool
	Position       int32
}

func (q *Queries) InsertVariant(ctx context.Context, arg InsertVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, insertVariant,
		arg.ProductID,
		arg.OrganizationID,
		arg.Name,
		arg.PriceCents,
		arg.IsDefault,
		arg.Position,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OrganizationID,
		&i.Name,
		&i.PriceCents,
		&i.IsDefault,
		&i.IsActive,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, organization_id, name, position, is_active, created_at, updated_at FROM categories WHERE organization_id = $1 ORDER BY position, id
`

func (q *Queries) ListCategories(ctx context.Context, organizationID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Position,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModifierGroupIDsByProducts = `-- name: ListModifierGroupIDsByProducts :many

SELECT product_id, modifier_group_id FROM product_modifier_groups WHERE product_id = ANY($1::uuid[]) ORDER BY product_id, position
`

type ListModifierGroupIDsByProductsRow struct {
	ProductID       uuid.UUID
	ModifierGroupID uuid.UUID
}

// ---------------------------------------------------------------------------
// Qué grupos de modificadores aplican a cada producto (N:M) — se reemplaza completo.
// ---------------------------------------------------------------------------
// Uno o varios product_id — mismo motivo que ListVariantsByProducts.
func (q *Queries) ListModifierGroupIDsByProducts(ctx context.Context, productIds []uuid.UUID) ([]ListModifierGroupIDsByProductsRow, error) {
	rows, err := q.db.Query(ctx, listModifierGroupIDsByProducts, productIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModifierGroupIDsByProductsRow{}
	for rows.Next() {
		var i ListModifierGroupIDsByProductsRow
		if err := rows.Scan(&i.ProductID, &i.ModifierGroupID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModifierGroups = `-- name: ListModifierGroups :many
SELECT id, organization_id, name, selection_type, min_select, max_select, is_active, created_at, updated_at FROM modifier_groups WHERE organization_id = $1 ORDER BY name, id
`

func (q *Queries) ListModifierGroups(ctx context.Context, organizationID uuid.UUID) ([]ModifierGroup, error) {
	rows, err := q.db.Query(ctx, listModifierGroups, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModifierGroup{}
	for rows.Next() {
		var i ModifierGroup
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.SelectionType,
			&i.MinSelect,
			&i.MaxSelect,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModifierOptionsByGroups = `-- name: ListModifierOptionsByGroups :many
SELECT id, modifier_group_id, organization_id, name, price_delta_cents, is_active, position, created_at, updated_at FROM modifier_options WHERE modifier_group_id = ANY($1::uuid[]) ORDER BY modifier_group_id, position, id
`

// Uno o varios modifier_group_id — mismo motivo que ListVariantsByProducts.
func (q *Queries) ListModifierOptionsByGroups(ctx context.Context, modifierGroupIds []uuid.UUID) ([]ModifierOption, error) {
	rows, err := q.db.Query(ctx, listModifierOptionsByGroups, modifierGroupIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModifierOption{}
	for rows.Next() {
		var i ModifierOption
		if err := rows.Scan(
			&i.ID,
			&i.ModifierGroupID,
			&i.OrganizationID,
			&i.Name,
			&i.PriceDeltaCents,
			&i.IsActive,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, organization_id, category_id, name, description, image_url, position, is_active, created_at, updated_at, ingredients, channels, promo_discount_bps FROM products
WHERE organization_id = $1
  AND ($2::uuid IS NULL OR category_id = $2)
ORDER BY position, id
LIMIT $4 OFFSET $3
`

type ListProductsParams struct {
	OrganizationID uuid.UUID
	CategoryID     uuid.NullUUID
	PageOffset     int32
	PageSize       int32
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.OrganizationID,
		arg.CategoryID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.Position,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Ingredients,
			&i.Channels,
			&i.PromoDiscountBps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicProducts = `-- name: ListPublicProducts :many

SELECT p.id, p.organization_id, o.name AS organization_name, o.slug AS organization_slug,
       s.logo_url AS organization_logo_url, p.category_id, c.name AS category_name,
       p.name, p.description, p.image_url, p.promo_discount_bps, MIN(v.price_cents)::int AS min_price_cents
FROM products p
JOIN organizations o ON o.id = p.organization_id
LEFT JOIN organization_settings s ON s.organization_id = o.id
LEFT JOIN categories c ON c.id = p.category_id
JOIN product_variants v ON v.product_id = p.id AND v.is_active
WHERE o.status = 'active' AND p.is_active AND 'ecommerce' = ANY(p.channels)
  AND ($1::uuid IS NULL OR p.organization_id = $1)
  AND ($2::text IS NULL OR o.slug = $2)
  AND ($3::text IS NULL OR p.name ILIKE '%' || $3::text || '%')
  AND ($4::text IS NULL OR c.name ILIKE $4::text)
GROUP BY p.id, p.organization_id, o.name, o.slug, s.logo_url, p.category_id, c.name, p.name, p.description, p.image_url,
         p.promo_discount_bps
ORDER BY p.created_at DESC, p.id
LIMIT $6 OFFSET $5
`

type ListPublicProductsParams struct {
	OrganizationID   uuid.NullUUID
	OrganizationSlug *string
	Search           *string
	Category         *string
	PageOffset       int32
	PageSize         int32
}

type ListPublicProductsRow struct {
	ID                  uuid.UUID
	OrganizationID      uuid.UUID
	OrganizationName    string
	OrganizationSlug    string
	OrganizationLogoUrl *string
	CategoryID          uuid.NullUUID
	CategoryName        *string
	Name                string
	Description         *string
	ImageUrl            *string
	PromoDiscountBps    int32
	MinPriceCents       int32
}

// ---------------------------------------------------------------------------
// Feed público: productos de VARIAS organizaciones a la vez (Inicio del cliente, estilo
// Rappi/UberEats/DiDi). Sin sesión, mismo criterio que ListPublicOrganizations: organización
// activa (o.status = 'active') y producto activo Y publicado a este canal
// ('ecommerce' = ANY(p.channels) — ver la migración 00009: una organización tiene que elegir
// publicar un producto a propósito, no basta con crearlo). El JOIN (no LEFT JOIN) con una
// variante activa excluye a propósito un producto sin nada que vender — no hay precio que
// mostrar ni variante que agregar al carrito.
//
// organization_id/organization_slug filtran al menú de UN restaurante (la vitrina de la
// organización los reutiliza — slug porque esa página solo conoce el slug de la URL, nunca el
// id); sin ninguno de los dos, cruza todas.
// ---------------------------------------------------------------------------
func (q *Queries) ListPublicProducts(ctx context.Context, arg ListPublicProductsParams) ([]ListPublicProductsRow, error) {
	rows, err := q.db.Query(ctx, listPublicProducts,
		arg.OrganizationID,
		arg.OrganizationSlug,
		arg.Search,
		arg.Category,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicProductsRow{}
	for rows.Next() {
		var i ListPublicProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.OrganizationSlug,
			&i.OrganizationLogoUrl,
			&i.CategoryID,
			&i.CategoryName,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.PromoDiscountBps,
			&i.MinPriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByProducts = `-- name: ListVariantsByProducts :many

SELECT id, product_id, organization_id, name, price_cents, is_default, is_active, position, created_at, updated_at FROM product_variants WHERE product_id = ANY($1::uuid[]) ORDER BY product_id, position, id
`

// ---------------------------------------------------------------------------
// Variantes — nunca DELETE real (docs/ecommerce.md §1.1.6): se reemplazan por upsert +
// desactivación de las que ya no vienen en la lista nueva.
// ---------------------------------------------------------------------------
// Recibe uno o varios product_id — así Get (un id) y List (una página completa) usan la misma
// consulta sin caer en N+1 al hidratar varios productos con sus variantes.
func (q *Queries) ListVariantsByProducts(ctx context.Context, productIds []uuid.UUID) ([]ProductVariant, error) {
	rows, err := q.db.Query(ctx, listVariantsByProducts, productIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductVariant{}
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.OrganizationID,
			&i.Name,
			&i.PriceCents,
			&i.IsDefault,
			&i.IsActive,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name       = COALESCE($1, name),
    position   = COALESCE($2, position),
    is_active  = COALESCE($3, is_active),
    updated_at = now()
WHERE id = $4 AND organization_id = $5
RETURNING id, organization_id, name, position, is_active, created_at, updated_at
`

type UpdateCategoryParams struct {
	Name           *string
	Position       *int32
	IsActive       *bool
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Name,
		arg.Position,
		arg.IsActive,
		arg.ID,
		arg.OrganizationID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Position,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateModifierGroup = `-- name: UpdateModifierGroup :one
UPDATE modifier_groups
SET name           = COALESCE($1, name),
    selection_type = COALESCE($2, selection_type),
    min_select     = COALESCE($3, min_select),
    max_select     = COALESCE($4, max_select),
    is_active      = COALESCE($5, is_active),
    updated_at     = now()
WHERE id = $6 AND organization_id = $7
RETURNING id, organization_id, name, selection_type, min_select, max_select, is_active, created_at, updated_at
`

type UpdateModifierGroupParams struct {
	Name           *string
	SelectionType  *string
	MinSelect      *int32
	MaxSelect      *int32
	IsActive       *bool
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) UpdateModifierGroup(ctx context.Context, arg UpdateModifierGroupParams) (ModifierGroup, error) {
	row := q.db.QueryRow(ctx, updateModifierGroup,
		arg.Name,
		arg.SelectionType,
		arg.MinSelect,
		arg.MaxSelect,
		arg.IsActive,
		arg.ID,
		arg.OrganizationID,
	)
	var i ModifierGroup
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.SelectionType,
		&i.MinSelect,
		&i.MaxSelect,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateModifierOption = `-- name: UpdateModifierOption :one
UPDATE modifier_options
SET name              = $1,
    price_delta_cents = $2,
    is_active         = true,
    position          = $3,
    updated_at        = now()
WHERE id = $4 AND modifier_group_id = $5 AND organization_id = $6
RETURNING id, modifier_group_id, organization_id, name, price_delta_cents, is_active, position, created_at, updated_at
`

type UpdateModifierOptionParams struct {
	Name            string
	PriceDeltaCents int32
	Position        int32
	ID              uuid.UUID
	ModifierGroupID uuid.UUID
	OrganizationID  uuid.UUID
}

func (q *Queries) UpdateModifierOption(ctx context.Context, arg UpdateModifierOptionParams) (ModifierOption, error) {
	row := q.db.QueryRow(ctx, updateModifierOption,
		arg.Name,
		arg.PriceDeltaCents,
		arg.Position,
		arg.ID,
		arg.ModifierGroupID,
		arg.OrganizationID,
	)
	var i ModifierOption
	err := row.Scan(
		&i.ID,
		&i.ModifierGroupID,
		&i.OrganizationID,
		&i.Name,
		&i.PriceDeltaCents,
		&i.IsActive,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET category_id  = CASE WHEN $1::boolean THEN $2 ELSE category_id END,
    name         = COALESCE($3, name),
    description  = CASE WHEN $4::boolean THEN $5 ELSE description END,
    image_url    = CASE WHEN $6::boolean THEN $7 ELSE image_url END,
    position     = COALESCE($8, position),
    is_active    = COALESCE($9, is_active),
    ingredients  = CASE WHEN $10::boolean THEN $11::text[] ELSE ingredients END,
    channels     = CASE WHEN $12::boolean THEN $13::text[] ELSE channels END,
    promo_discount_bps = COALESCE($14, promo_discount_bps),
    updated_at   = now()
WHERE id = $15 AND organization_id = $16
RETURNING id, organization_id, category_id, name, description, image_url, position, is_active, created_at, updated_at, ingredients, channels, promo_discount_bps
`

type UpdateProductParams struct {
	SetCategory      bool
	CategoryID       uuid.NullUUID
	Name             *string
	SetDescription   bool
	Description      *string
	SetImage         bool
	ImageUrl         *string
	Position         *int32
	IsActive         *bool
	SetIngredients   bool
	Ingredients      []string
	SetChannels      bool
	Channels         []string
	PromoDiscountBps *int32
	ID               uuid.UUID
	OrganizationID   uuid.UUID
}

// Cambio parcial: set_* distingue "no tocar" de "reemplazar" para los campos que no se pueden
// expresar con un simple ausente (category_id/description/image_url admiten null; ingredients y
// channels son arreglos, y un arreglo vacío es un valor real — "sin ingredientes", "sin publicar
// en ningún canal" — no "no tocar"). name/position/is_active nunca se ponen en blanco, así que
// un ausente (COALESCE) basta ahí.
func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.SetCategory,
		arg.CategoryID,
		arg.Name,
		arg.SetDescription,
		arg.Description,
		arg.SetImage,
		arg.ImageUrl,
		arg.Position,
		arg.IsActive,
		arg.SetIngredients,
		arg.Ingredients,
		arg.SetChannels,
		arg.Channels,
		arg.PromoDiscountBps,
		arg.ID,
		arg.OrganizationID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.Position,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Ingredients,
		&i.Channels,
		&i.PromoDiscountBps,
	)
	return i, err
}

const updateVariant = `-- name: UpdateVariant :one
UPDATE product_variants
SET name        = $1,
    price_cents = $2,
    is_default  = $3,
    is_active   = true,
    position    = $4,
    updated_at  = now()
WHERE id = $5 AND product_id = $6 AND organization_id = $7
RETURNING id, product_id, organization_id, name, price_cents, is_default, is_active, position, created_at, updated_at
`

type UpdateVariantParams struct {
	Name           string
	PriceCents     int32
	IsDefault      bool
	Position       int32
	ID             uuid.UUID
	ProductID      uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, updateVariant,
		arg.Name,
		arg.PriceCents,
		arg.IsDefault,
		arg.Position,
		arg.ID,
		arg.ProductID,
		arg.OrganizationID,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OrganizationID,
		&i.Name,
		&i.PriceCents,
		&i.IsDefault,
		&i.IsActive,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
