// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getContact = `-- name: GetContact :one
SELECT id, organization_id, phone_e164, name, email, customer_user_id, custom_attributes, blocked, source, last_activity_at, created_at, updated_at FROM contacts WHERE id = $1 AND organization_id = $2
`

type GetContactParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) GetContact(ctx context.Context, arg GetContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContact, arg.ID, arg.OrganizationID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PhoneE164,
		&i.Name,
		&i.Email,
		&i.CustomerUserID,
		&i.CustomAttributes,
		&i.Blocked,
		&i.Source,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertContact = `-- name: InsertContact :one
INSERT INTO contacts (organization_id, phone_e164, name, email, custom_attributes, source)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, phone_e164, name, email, customer_user_id, custom_attributes, blocked, source, last_activity_at, created_at, updated_at
`

type InsertContactParams struct {
	OrganizationID   uuid.UUID
	PhoneE164        string
	Name             *string
	Email            *string
	CustomAttributes []byte
	Source           string
}

func (q *Queries) InsertContact(ctx context.Context, arg InsertContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, insertContact,
		arg.OrganizationID,
		arg.PhoneE164,
		arg.Name,
		arg.Email,
		arg.CustomAttributes,
		arg.Source,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PhoneE164,
		&i.Name,
		&i.Email,
		&i.CustomerUserID,
		&i.CustomAttributes,
		&i.Blocked,
		&i.Source,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContacts = `-- name: ListContacts :many
SELECT id, organization_id, phone_e164, name, email, customer_user_id, custom_attributes, blocked, source, last_activity_at, created_at, updated_at FROM contacts
WHERE organization_id = $1
  AND ($2::text IS NULL
        OR name ILIKE '%' || $2::text || '%'
        OR phone_e164 LIKE '%' || $2::text || '%'
        OR email ILIKE '%' || $2::text || '%')
  AND ($3::timestamptz IS NULL
        OR (created_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListContactsParams struct {
	OrganizationID uuid.UUID
	Search         *string
	BeforeAt       pgtype.Timestamptz
	BeforeID       uuid.NullUUID
	PageSize       int32
}

// Listado por creación (el más nuevo primero) con cursor. `search` ya viene escapado para LIKE.
func (q *Queries) ListContacts(ctx context.Context, arg ListContactsParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContacts,
		arg.OrganizationID,
		arg.Search,
		arg.BeforeAt,
		arg.BeforeID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PhoneE164,
			&i.Name,
			&i.Email,
			&i.CustomerUserID,
			&i.CustomAttributes,
			&i.Blocked,
			&i.Source,
			&i.LastActivityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts
SET name = CASE WHEN $1::boolean THEN $2 ELSE name END,
    email = CASE WHEN $3::boolean THEN $4 ELSE email END,
    custom_attributes = COALESCE($5::jsonb, custom_attributes),
    blocked = COALESCE($6::boolean, blocked),
    updated_at = now()
WHERE id = $7 AND organization_id = $8
RETURNING id, organization_id, phone_e164, name, email, customer_user_id, custom_attributes, blocked, source, last_activity_at, created_at, updated_at
`

type UpdateContactParams struct {
	SetName          bool
	Name             *string
	SetEmail         bool
	Email            *string
	CustomAttributes []byte
	Blocked          *bool
	ID               uuid.UUID
	OrganizationID   uuid.UUID
}

// Cambio parcial: set_* distingue "no tocar" de "dejar en blanco".
func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.SetName,
		arg.Name,
		arg.SetEmail,
		arg.Email,
		arg.CustomAttributes,
		arg.Blocked,
		arg.ID,
		arg.OrganizationID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PhoneE164,
		&i.Name,
		&i.Email,
		&i.CustomerUserID,
		&i.CustomAttributes,
		&i.Blocked,
		&i.Source,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertContactByPhone = `-- name: UpsertContactByPhone :one
INSERT INTO contacts (organization_id, phone_e164, name, source, last_activity_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (organization_id, phone_e164)
DO UPDATE SET name = COALESCE(contacts.name, EXCLUDED.name),
              last_activity_at = now(), updated_at = now()
RETURNING id, organization_id, phone_e164, name, email, customer_user_id, custom_attributes, blocked, source, last_activity_at, created_at, updated_at
`

type UpsertContactByPhoneParams struct {
	OrganizationID uuid.UUID
	PhoneE164      string
	Name           *string
	Source         string
}

// Alta o actualización por teléfono, a prueba de carreras: dos mensajes simultáneos de una persona
// nueva no chocan. El nombre del perfil de WhatsApp solo se usa si el contacto aún no tiene nombre.
func (q *Queries) UpsertContactByPhone(ctx context.Context, arg UpsertContactByPhoneParams) (Contact, error) {
	row := q.db.QueryRow(ctx, upsertContactByPhone,
		arg.OrganizationID,
		arg.PhoneE164,
		arg.Name,
		arg.Source,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PhoneE164,
		&i.Name,
		&i.Email,
		&i.CustomerUserID,
		&i.CustomAttributes,
		&i.Blocked,
		&i.Source,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
