// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyMessageStatus = `-- name: ApplyMessageStatus :execrows
UPDATE messages
SET status = $1,
    sent_at = CASE WHEN $1 IN ('sent', 'delivered', 'read') THEN COALESCE(sent_at, $2) ELSE sent_at END,
    delivered_at = CASE WHEN $1 IN ('delivered', 'read') THEN COALESCE(delivered_at, $2) ELSE delivered_at END,
    read_at = CASE WHEN $1 = 'read' THEN COALESCE(read_at, $2) ELSE read_at END,
    failed_at = CASE WHEN $1 = 'failed' THEN COALESCE(failed_at, $2) ELSE failed_at END,
    error_code = CASE WHEN $1 = 'failed' THEN $3 ELSE error_code END,
    error_detail = CASE WHEN $1 = 'failed' THEN $4 ELSE error_detail END,
    pricing_category = COALESCE($5, pricing_category),
    billable = COALESCE($6, billable),
    locked_until = NULL, next_attempt_at = NULL
WHERE inbox_id = $7 AND wamid = $8 AND direction = 'outbound'
  AND (
      ($1 IN ('sent', 'delivered', 'read') AND
        CASE status WHEN 'queued' THEN 0 WHEN 'sent' THEN 1 WHEN 'delivered' THEN 2 WHEN 'read' THEN 3 ELSE 99 END
        < CASE $1::text WHEN 'sent' THEN 1 WHEN 'delivered' THEN 2 WHEN 'read' THEN 3 ELSE 0 END)
      OR ($1 = 'failed' AND status IN ('queued', 'sent'))
  )
`

type ApplyMessageStatusParams struct {
	Status          string
	At              pgtype.Timestamptz
	ErrorCode       *string
	ErrorDetail     *string
	PricingCategory *string
	Billable        *bool
	InboxID         uuid.UUID
	Wamid           *string
}

// Estado de un mensaje nuestro que llegó por webhook. Solo AVANZA: queued < sent < delivered < read;
// "failed" puede llegar mientras no se haya entregado; nada retrocede (Meta no garantiza el orden).
func (q *Queries) ApplyMessageStatus(ctx context.Context, arg ApplyMessageStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyMessageStatus,
		arg.Status,
		arg.At,
		arg.ErrorCode,
		arg.ErrorDetail,
		arg.PricingCategory,
		arg.Billable,
		arg.InboxID,
		arg.Wamid,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimOutbox = `-- name: ClaimOutbox :many

WITH due AS (
    SELECT m.id FROM messages m
    WHERE m.direction = 'outbound' AND m.status = 'queued'
      AND m.next_attempt_at <= now() AND (m.locked_until IS NULL OR m.locked_until < now())
      -- Solo el mensaje más viejo de cada conversación: se entregan EN ORDEN y nunca dos a la vez.
      AND NOT EXISTS (SELECT 1 FROM messages e
                      WHERE e.conversation_id = m.conversation_id AND e.direction = 'outbound'
                        AND e.status = 'queued' AND (e.created_at, e.id) < (m.created_at, m.id))
    ORDER BY m.next_attempt_at, m.created_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
UPDATE messages m
SET locked_until = now() + make_interval(secs => $1::int), attempts = m.attempts + 1
FROM due WHERE m.id = due.id
RETURNING m.id, m.organization_id, m.conversation_id, m.inbox_id, m.direction, m.kind, m.body, m.wamid, m.status, m.error_code, m.error_detail, m.attempts, m.next_attempt_at, m.locked_until, m.sent_at, m.delivered_at, m.read_at, m.failed_at, m.sender_user_id, m.reply_to_message_id, m.payload, m.pricing_category, m.billable, m.created_at
`

type ClaimOutboxParams struct {
	LeaseSeconds int32
	BatchSize    int32
}

// ---------------------------------------------------------------------------
// Cola de salida
// ---------------------------------------------------------------------------
// Reclama mensajes listos para enviar con un arrendamiento: dos trabajadores nunca toman el mismo
// mensaje, y si uno muere el arrendamiento vence y otro lo retoma.
func (q *Queries) ClaimOutbox(ctx context.Context, arg ClaimOutboxParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, claimOutbox, arg.LeaseSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ConversationID,
			&i.InboxID,
			&i.Direction,
			&i.Kind,
			&i.Body,
			&i.Wamid,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorDetail,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LockedUntil,
			&i.SentAt,
			&i.DeliveredAt,
			&i.ReadAt,
			&i.FailedAt,
			&i.SenderUserID,
			&i.ReplyToMessageID,
			&i.Payload,
			&i.PricingCategory,
			&i.Billable,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countConversationTabs = `-- name: CountConversationTabs :one
SELECT count(*) FILTER (WHERE assignee_id = $1::uuid) AS mine,
       count(*) FILTER (WHERE assignee_id IS NULL) AS unassigned,
       count(*) AS total
FROM conversations
WHERE organization_id = $2
  AND ($3::uuid IS NULL OR inbox_id = $3::uuid)
  AND ($4::text IS NULL OR status = $4::text)
`

type CountConversationTabsParams struct {
	UserID         uuid.NullUUID
	OrganizationID uuid.UUID
	InboxID        uuid.NullUUID
	Status         *string
}

type CountConversationTabsRow struct {
	Mine       int64
	Unassigned int64
	Total      int64
}

// Pestañas de la bandeja: mías, sin asignar, todas.
func (q *Queries) CountConversationTabs(ctx context.Context, arg CountConversationTabsParams) (CountConversationTabsRow, error) {
	row := q.db.QueryRow(ctx, countConversationTabs,
		arg.UserID,
		arg.OrganizationID,
		arg.InboxID,
		arg.Status,
	)
	var i CountConversationTabsRow
	err := row.Scan(&i.Mine, &i.Unassigned, &i.Total)
	return i, err
}

const deleteUnmatchedStatuses = `-- name: DeleteUnmatchedStatuses :exec
DELETE FROM unmatched_statuses WHERE wamid = $1
`

func (q *Queries) DeleteUnmatchedStatuses(ctx context.Context, wamid string) error {
	_, err := q.db.Exec(ctx, deleteUnmatchedStatuses, wamid)
	return err
}

const getActiveConversationForUpdate = `-- name: GetActiveConversationForUpdate :one
SELECT id, organization_id, inbox_id, contact_id, display_id, status, priority, assignee_id, handled_by, last_customer_message_at, last_activity_at, last_message_preview, last_message_direction, first_response_at, waiting_since, snoozed_until, unread_count, created_at, updated_at FROM conversations
WHERE inbox_id = $1 AND contact_id = $2 AND organization_id = $3 AND status <> 'resolved'
FOR UPDATE
`

type GetActiveConversationForUpdateParams struct {
	InboxID        uuid.UUID
	ContactID      uuid.UUID
	OrganizationID uuid.UUID
}

// La conversación abierta (no resuelta) de un contacto en una bandeja, bloqueada para actualizarla.
func (q *Queries) GetActiveConversationForUpdate(ctx context.Context, arg GetActiveConversationForUpdateParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getActiveConversationForUpdate, arg.InboxID, arg.ContactID, arg.OrganizationID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InboxID,
		&i.ContactID,
		&i.DisplayID,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.HandledBy,
		&i.LastCustomerMessageAt,
		&i.LastActivityAt,
		&i.LastMessagePreview,
		&i.LastMessageDirection,
		&i.FirstResponseAt,
		&i.WaitingSince,
		&i.SnoozedUntil,
		&i.UnreadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT c.id, c.organization_id, c.inbox_id, c.contact_id, c.display_id, c.status, c.priority, c.assignee_id, c.handled_by, c.last_customer_message_at, c.last_activity_at, c.last_message_preview, c.last_message_direction, c.first_response_at, c.waiting_since, c.snoozed_until, c.unread_count, c.created_at, c.updated_at, ct.name AS contact_name, ct.phone_e164 AS contact_phone, ct.blocked AS contact_blocked,
       wc.status AS channel_status
FROM conversations c
JOIN contacts ct ON ct.id = c.contact_id
LEFT JOIN whatsapp_channels wc ON wc.inbox_id = c.inbox_id
WHERE c.id = $1 AND c.organization_id = $2
`

type GetConversationParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

type GetConversationRow struct {
	ID                    uuid.UUID
	OrganizationID        uuid.UUID
	InboxID               uuid.UUID
	ContactID             uuid.UUID
	DisplayID             int64
	Status                string
	Priority              *string
	AssigneeID            uuid.NullUUID
	HandledBy             string
	LastCustomerMessageAt pgtype.Timestamptz
	LastActivityAt        time.Time
	LastMessagePreview    *string
	LastMessageDirection  *string
	FirstResponseAt       pgtype.Timestamptz
	WaitingSince          pgtype.Timestamptz
	SnoozedUntil          pgtype.Timestamptz
	UnreadCount           int32
	CreatedAt             time.Time
	UpdatedAt             time.Time
	ContactName           *string
	ContactPhone          string
	ContactBlocked        bool
	ChannelStatus         *string
}

// channel_status es NULL si la bandeja ya no tiene número conectado (archivada).
func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (GetConversationRow, error) {
	row := q.db.QueryRow(ctx, getConversation, arg.ID, arg.OrganizationID)
	var i GetConversationRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InboxID,
		&i.ContactID,
		&i.DisplayID,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.HandledBy,
		&i.LastCustomerMessageAt,
		&i.LastActivityAt,
		&i.LastMessagePreview,
		&i.LastMessageDirection,
		&i.FirstResponseAt,
		&i.WaitingSince,
		&i.SnoozedUntil,
		&i.UnreadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContactName,
		&i.ContactPhone,
		&i.ContactBlocked,
		&i.ChannelStatus,
	)
	return i, err
}

const getConversationForUpdate = `-- name: GetConversationForUpdate :one
SELECT id, organization_id, inbox_id, contact_id, display_id, status, priority, assignee_id, handled_by, last_customer_message_at, last_activity_at, last_message_preview, last_message_direction, first_response_at, waiting_since, snoozed_until, unread_count, created_at, updated_at FROM conversations WHERE id = $1 AND organization_id = $2 FOR UPDATE
`

type GetConversationForUpdateParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) GetConversationForUpdate(ctx context.Context, arg GetConversationForUpdateParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationForUpdate, arg.ID, arg.OrganizationID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InboxID,
		&i.ContactID,
		&i.DisplayID,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.HandledBy,
		&i.LastCustomerMessageAt,
		&i.LastActivityAt,
		&i.LastMessagePreview,
		&i.LastMessageDirection,
		&i.FirstResponseAt,
		&i.WaitingSince,
		&i.SnoozedUntil,
		&i.UnreadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, organization_id, conversation_id, inbox_id, direction, kind, body, wamid, status, error_code, error_detail, attempts, next_attempt_at, locked_until, sent_at, delivered_at, read_at, failed_at, sender_user_id, reply_to_message_id, payload, pricing_category, billable, created_at FROM messages WHERE id = $1 AND organization_id = $2
`

type GetMessageParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) GetMessage(ctx context.Context, arg GetMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, arg.ID, arg.OrganizationID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ConversationID,
		&i.InboxID,
		&i.Direction,
		&i.Kind,
		&i.Body,
		&i.Wamid,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReadAt,
		&i.FailedAt,
		&i.SenderUserID,
		&i.ReplyToMessageID,
		&i.Payload,
		&i.PricingCategory,
		&i.Billable,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageByWamid = `-- name: GetMessageByWamid :one
SELECT id, organization_id, conversation_id, inbox_id, direction, kind, body, wamid, status, error_code, error_detail, attempts, next_attempt_at, locked_until, sent_at, delivered_at, read_at, failed_at, sender_user_id, reply_to_message_id, payload, pricing_category, billable, created_at FROM messages WHERE inbox_id = $1 AND wamid = $2
`

type GetMessageByWamidParams struct {
	InboxID uuid.UUID
	Wamid   *string
}

func (q *Queries) GetMessageByWamid(ctx context.Context, arg GetMessageByWamidParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByWamid, arg.InboxID, arg.Wamid)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ConversationID,
		&i.InboxID,
		&i.Direction,
		&i.Kind,
		&i.Body,
		&i.Wamid,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReadAt,
		&i.FailedAt,
		&i.SenderUserID,
		&i.ReplyToMessageID,
		&i.Payload,
		&i.PricingCategory,
		&i.Billable,
		&i.CreatedAt,
	)
	return i, err
}

const insertConversation = `-- name: InsertConversation :one
INSERT INTO conversations (organization_id, inbox_id, contact_id, display_id, last_activity_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (inbox_id, contact_id) WHERE status <> 'resolved' DO NOTHING
RETURNING id, organization_id, inbox_id, contact_id, display_id, status, priority, assignee_id, handled_by, last_customer_message_at, last_activity_at, last_message_preview, last_message_direction, first_response_at, waiting_since, snoozed_until, unread_count, created_at, updated_at
`

type InsertConversationParams struct {
	OrganizationID uuid.UUID
	InboxID        uuid.UUID
	ContactID      uuid.UUID
	DisplayID      int64
	LastActivityAt time.Time
}

func (q *Queries) InsertConversation(ctx context.Context, arg InsertConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, insertConversation,
		arg.OrganizationID,
		arg.InboxID,
		arg.ContactID,
		arg.DisplayID,
		arg.LastActivityAt,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InboxID,
		&i.ContactID,
		&i.DisplayID,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.HandledBy,
		&i.LastCustomerMessageAt,
		&i.LastActivityAt,
		&i.LastMessagePreview,
		&i.LastMessageDirection,
		&i.FirstResponseAt,
		&i.WaitingSince,
		&i.SnoozedUntil,
		&i.UnreadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertInboundMessage = `-- name: InsertInboundMessage :one

INSERT INTO messages (organization_id, conversation_id, inbox_id, direction, kind, body, wamid, status, payload,
                      reply_to_message_id, created_at)
VALUES ($1, $2, $3, 'inbound', $4, $5, $6, 'received', $7,
        $8, $9)
ON CONFLICT (inbox_id, wamid) WHERE wamid IS NOT NULL DO NOTHING
RETURNING id, organization_id, conversation_id, inbox_id, direction, kind, body, wamid, status, error_code, error_detail, attempts, next_attempt_at, locked_until, sent_at, delivered_at, read_at, failed_at, sender_user_id, reply_to_message_id, payload, pricing_category, billable, created_at
`

type InsertInboundMessageParams struct {
	OrganizationID   uuid.UUID
	ConversationID   uuid.UUID
	InboxID          uuid.UUID
	Kind             string
	Body             *string
	Wamid            *string
	Payload          []byte
	ReplyToMessageID uuid.NullUUID
	CreatedAt        time.Time
}

// ---------------------------------------------------------------------------
// Mensajes
// ---------------------------------------------------------------------------
// Entrante. Si el wamid ya existe (reentrega de Meta) no inserta y no devuelve fila.
func (q *Queries) InsertInboundMessage(ctx context.Context, arg InsertInboundMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertInboundMessage,
		arg.OrganizationID,
		arg.ConversationID,
		arg.InboxID,
		arg.Kind,
		arg.Body,
		arg.Wamid,
		arg.Payload,
		arg.ReplyToMessageID,
		arg.CreatedAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ConversationID,
		&i.InboxID,
		&i.Direction,
		&i.Kind,
		&i.Body,
		&i.Wamid,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReadAt,
		&i.FailedAt,
		&i.SenderUserID,
		&i.ReplyToMessageID,
		&i.Payload,
		&i.PricingCategory,
		&i.Billable,
		&i.CreatedAt,
	)
	return i, err
}

const insertMessageAttachment = `-- name: InsertMessageAttachment :exec
INSERT INTO message_attachments (organization_id, message_id, kind, mime_type, filename, size_bytes, sha256, wa_media_id, caption)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9)
`

type InsertMessageAttachmentParams struct {
	OrganizationID uuid.UUID
	MessageID      uuid.UUID
	Kind           string
	MimeType       *string
	Filename       *string
	SizeBytes      *int64
	Sha256         *string
	WaMediaID      *string
	Caption        *string
}

func (q *Queries) InsertMessageAttachment(ctx context.Context, arg InsertMessageAttachmentParams) error {
	_, err := q.db.Exec(ctx, insertMessageAttachment,
		arg.OrganizationID,
		arg.MessageID,
		arg.Kind,
		arg.MimeType,
		arg.Filename,
		arg.SizeBytes,
		arg.Sha256,
		arg.WaMediaID,
		arg.Caption,
	)
	return err
}

const insertOutboundMessage = `-- name: InsertOutboundMessage :one
INSERT INTO messages (organization_id, conversation_id, inbox_id, direction, kind, body, status, next_attempt_at,
                      sender_user_id, reply_to_message_id)
VALUES ($1, $2, $3, 'outbound', $4, $5, 'queued', now(),
        $6, $7)
RETURNING id, organization_id, conversation_id, inbox_id, direction, kind, body, wamid, status, error_code, error_detail, attempts, next_attempt_at, locked_until, sent_at, delivered_at, read_at, failed_at, sender_user_id, reply_to_message_id, payload, pricing_category, billable, created_at
`

type InsertOutboundMessageParams struct {
	OrganizationID   uuid.UUID
	ConversationID   uuid.UUID
	InboxID          uuid.UUID
	Kind             string
	Body             *string
	SenderUserID     uuid.NullUUID
	ReplyToMessageID uuid.NullUUID
}

func (q *Queries) InsertOutboundMessage(ctx context.Context, arg InsertOutboundMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertOutboundMessage,
		arg.OrganizationID,
		arg.ConversationID,
		arg.InboxID,
		arg.Kind,
		arg.Body,
		arg.SenderUserID,
		arg.ReplyToMessageID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ConversationID,
		&i.InboxID,
		&i.Direction,
		&i.Kind,
		&i.Body,
		&i.Wamid,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReadAt,
		&i.FailedAt,
		&i.SenderUserID,
		&i.ReplyToMessageID,
		&i.Payload,
		&i.PricingCategory,
		&i.Billable,
		&i.CreatedAt,
	)
	return i, err
}

const insertUnmatchedStatus = `-- name: InsertUnmatchedStatus :exec
INSERT INTO unmatched_statuses (wamid, status, occurred_at, error_code, error_detail, pricing_category, billable)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertUnmatchedStatusParams struct {
	Wamid           string
	Status          string
	OccurredAt      time.Time
	ErrorCode       *string
	ErrorDetail     *string
	PricingCategory *string
	Billable        *bool
}

func (q *Queries) InsertUnmatchedStatus(ctx context.Context, arg InsertUnmatchedStatusParams) error {
	_, err := q.db.Exec(ctx, insertUnmatchedStatus,
		arg.Wamid,
		arg.Status,
		arg.OccurredAt,
		arg.ErrorCode,
		arg.ErrorDetail,
		arg.PricingCategory,
		arg.Billable,
	)
	return err
}

const listAttachmentsForMessages = `-- name: ListAttachmentsForMessages :many
SELECT id, organization_id, message_id, kind, mime_type, filename, size_bytes, sha256, wa_media_id, caption, created_at FROM message_attachments WHERE message_id = ANY($1::uuid[]) ORDER BY created_at, id
`

func (q *Queries) ListAttachmentsForMessages(ctx context.Context, messageIds []uuid.UUID) ([]MessageAttachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsForMessages, messageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageAttachment{}
	for rows.Next() {
		var i MessageAttachment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MessageID,
			&i.Kind,
			&i.MimeType,
			&i.Filename,
			&i.SizeBytes,
			&i.Sha256,
			&i.WaMediaID,
			&i.Caption,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversations = `-- name: ListConversations :many
SELECT c.id, c.organization_id, c.inbox_id, c.contact_id, c.display_id, c.status, c.priority, c.assignee_id, c.handled_by, c.last_customer_message_at, c.last_activity_at, c.last_message_preview, c.last_message_direction, c.first_response_at, c.waiting_since, c.snoozed_until, c.unread_count, c.created_at, c.updated_at, ct.name AS contact_name, ct.phone_e164 AS contact_phone, ct.blocked AS contact_blocked,
       wc.status AS channel_status
FROM conversations c
JOIN contacts ct ON ct.id = c.contact_id
LEFT JOIN whatsapp_channels wc ON wc.inbox_id = c.inbox_id
WHERE c.organization_id = $1
  AND ($2::uuid IS NULL OR c.inbox_id = $2::uuid)
  AND ($3::text IS NULL OR c.status = $3::text)
  AND ($4::text = 'all'
        OR ($4::text = 'unassigned' AND c.assignee_id IS NULL)
        OR ($4::text IN ('me', 'user') AND c.assignee_id = $5::uuid))
  AND ($6::text IS NULL
        OR ct.name ILIKE '%' || $6::text || '%'
        OR ct.phone_e164 LIKE '%' || $6::text || '%')
  AND ($7::timestamptz IS NULL
        OR (c.last_activity_at, c.id) < ($7::timestamptz, $8::uuid))
ORDER BY c.last_activity_at DESC, c.id DESC
LIMIT $9
`

type ListConversationsParams struct {
	OrganizationID uuid.UUID
	InboxID        uuid.NullUUID
	Status         *string
	AssigneeMode   string
	AssigneeID     uuid.NullUUID
	Search         *string
	BeforeAt       pgtype.Timestamptz
	BeforeID       uuid.NullUUID
	PageSize       int32
}

type ListConversationsRow struct {
	ID                    uuid.UUID
	OrganizationID        uuid.UUID
	InboxID               uuid.UUID
	ContactID             uuid.UUID
	DisplayID             int64
	Status                string
	Priority              *string
	AssigneeID            uuid.NullUUID
	HandledBy             string
	LastCustomerMessageAt pgtype.Timestamptz
	LastActivityAt        time.Time
	LastMessagePreview    *string
	LastMessageDirection  *string
	FirstResponseAt       pgtype.Timestamptz
	WaitingSince          pgtype.Timestamptz
	SnoozedUntil          pgtype.Timestamptz
	UnreadCount           int32
	CreatedAt             time.Time
	UpdatedAt             time.Time
	ContactName           *string
	ContactPhone          string
	ContactBlocked        bool
	ChannelStatus         *string
}

// Listado con cursor por actividad. `assignee_mode`: all | me | unassigned | user. `search` ya viene
// escapado para LIKE.
func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]ListConversationsRow, error) {
	rows, err := q.db.Query(ctx, listConversations,
		arg.OrganizationID,
		arg.InboxID,
		arg.Status,
		arg.AssigneeMode,
		arg.AssigneeID,
		arg.Search,
		arg.BeforeAt,
		arg.BeforeID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationsRow{}
	for rows.Next() {
		var i ListConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.InboxID,
			&i.ContactID,
			&i.DisplayID,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.HandledBy,
			&i.LastCustomerMessageAt,
			&i.LastActivityAt,
			&i.LastMessagePreview,
			&i.LastMessageDirection,
			&i.FirstResponseAt,
			&i.WaitingSince,
			&i.SnoozedUntil,
			&i.UnreadCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContactName,
			&i.ContactPhone,
			&i.ContactBlocked,
			&i.ChannelStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, organization_id, conversation_id, inbox_id, direction, kind, body, wamid, status, error_code, error_detail, attempts, next_attempt_at, locked_until, sent_at, delivered_at, read_at, failed_at, sender_user_id, reply_to_message_id, payload, pricing_category, billable, created_at FROM messages
WHERE conversation_id = $1 AND organization_id = $2
  AND ($3::timestamptz IS NULL
        OR (created_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListMessagesParams struct {
	ConversationID uuid.UUID
	OrganizationID uuid.UUID
	BeforeAt       pgtype.Timestamptz
	BeforeID       uuid.NullUUID
	PageSize       int32
}

// Hilo de una conversación, del más nuevo al más viejo, con cursor.
func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages,
		arg.ConversationID,
		arg.OrganizationID,
		arg.BeforeAt,
		arg.BeforeID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ConversationID,
			&i.InboxID,
			&i.Direction,
			&i.Kind,
			&i.Body,
			&i.Wamid,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorDetail,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LockedUntil,
			&i.SentAt,
			&i.DeliveredAt,
			&i.ReadAt,
			&i.FailedAt,
			&i.SenderUserID,
			&i.ReplyToMessageID,
			&i.Payload,
			&i.PricingCategory,
			&i.Billable,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnmatchedStatuses = `-- name: ListUnmatchedStatuses :many
SELECT id, wamid, status, occurred_at, error_code, error_detail, pricing_category, billable, created_at FROM unmatched_statuses WHERE wamid = $1 ORDER BY occurred_at, created_at
`

func (q *Queries) ListUnmatchedStatuses(ctx context.Context, wamid string) ([]UnmatchedStatus, error) {
	rows, err := q.db.Query(ctx, listUnmatchedStatuses, wamid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnmatchedStatus{}
	for rows.Next() {
		var i UnmatchedStatus
		if err := rows.Scan(
			&i.ID,
			&i.Wamid,
			&i.Status,
			&i.OccurredAt,
			&i.ErrorCode,
			&i.ErrorDetail,
			&i.PricingCategory,
			&i.Billable,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConversationRead = `-- name: MarkConversationRead :exec
UPDATE conversations SET unread_count = 0, updated_at = now()
WHERE id = $1 AND organization_id = $2 AND unread_count <> 0
`

type MarkConversationReadParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) MarkConversationRead(ctx context.Context, arg MarkConversationReadParams) error {
	_, err := q.db.Exec(ctx, markConversationRead, arg.ID, arg.OrganizationID)
	return err
}

const markMessageFailed = `-- name: MarkMessageFailed :exec
UPDATE messages
SET status = 'failed', failed_at = now(), locked_until = NULL, next_attempt_at = NULL,
    error_code = $1, error_detail = $2
WHERE id = $3 AND organization_id = $4 AND status IN ('queued')
`

type MarkMessageFailedParams struct {
	ErrorCode      *string
	ErrorDetail    *string
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) MarkMessageFailed(ctx context.Context, arg MarkMessageFailedParams) error {
	_, err := q.db.Exec(ctx, markMessageFailed,
		arg.ErrorCode,
		arg.ErrorDetail,
		arg.ID,
		arg.OrganizationID,
	)
	return err
}

const markMessageSent = `-- name: MarkMessageSent :exec
UPDATE messages
SET status = CASE WHEN status = 'queued' THEN 'sent' ELSE status END,
    wamid = $1, sent_at = COALESCE(sent_at, now()), locked_until = NULL, next_attempt_at = NULL,
    error_code = NULL, error_detail = NULL
WHERE id = $2 AND organization_id = $3
`

type MarkMessageSentParams struct {
	Wamid          *string
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) MarkMessageSent(ctx context.Context, arg MarkMessageSentParams) error {
	_, err := q.db.Exec(ctx, markMessageSent, arg.Wamid, arg.ID, arg.OrganizationID)
	return err
}

const markWebhookFailed = `-- name: MarkWebhookFailed :exec
UPDATE webhook_events SET error = $1 WHERE id = $2
`

type MarkWebhookFailedParams struct {
	Error *string
	ID    uuid.UUID
}

func (q *Queries) MarkWebhookFailed(ctx context.Context, arg MarkWebhookFailedParams) error {
	_, err := q.db.Exec(ctx, markWebhookFailed, arg.Error, arg.ID)
	return err
}

const markWebhookProcessed = `-- name: MarkWebhookProcessed :exec
UPDATE webhook_events SET processed_at = now(), error = NULL WHERE id = $1
`

func (q *Queries) MarkWebhookProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markWebhookProcessed, id)
	return err
}

const nextConversationDisplayID = `-- name: NextConversationDisplayID :one
INSERT INTO organization_counters (organization_id, conversation_seq) VALUES ($1, 1)
ON CONFLICT (organization_id) DO UPDATE SET conversation_seq = organization_counters.conversation_seq + 1
RETURNING conversation_seq
`

// Número de conversación por organización (#1, #2...), sin huecos ni repetidos aunque haya
// altas simultáneas: la fila del contador se bloquea dentro de la transacción del alta.
func (q *Queries) NextConversationDisplayID(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextConversationDisplayID, organizationID)
	var conversation_seq int64
	err := row.Scan(&conversation_seq)
	return conversation_seq, err
}

const pruneUnmatchedStatuses = `-- name: PruneUnmatchedStatuses :execrows
DELETE FROM unmatched_statuses WHERE created_at < now() - interval '1 day'
`

func (q *Queries) PruneUnmatchedStatuses(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneUnmatchedStatuses)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneWebhookEvents = `-- name: PruneWebhookEvents :execrows
DELETE FROM webhook_events WHERE received_at < now() - interval '30 days'
`

func (q *Queries) PruneWebhookEvents(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneWebhookEvents)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scheduleMessageRetry = `-- name: ScheduleMessageRetry :exec
UPDATE messages
SET next_attempt_at = $1, locked_until = NULL, error_code = $2, error_detail = $3
WHERE id = $4 AND organization_id = $5 AND status = 'queued'
`

type ScheduleMessageRetryParams struct {
	NextAttemptAt  pgtype.Timestamptz
	ErrorCode      *string
	ErrorDetail    *string
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) ScheduleMessageRetry(ctx context.Context, arg ScheduleMessageRetryParams) error {
	_, err := q.db.Exec(ctx, scheduleMessageRetry,
		arg.NextAttemptAt,
		arg.ErrorCode,
		arg.ErrorDetail,
		arg.ID,
		arg.OrganizationID,
	)
	return err
}

const touchConversationInbound = `-- name: TouchConversationInbound :exec
UPDATE conversations
SET last_customer_message_at = GREATEST(last_customer_message_at, $1),
    last_activity_at = GREATEST(last_activity_at, $1),
    last_message_preview = CASE WHEN last_message_preview IS NULL OR $1 >= last_activity_at THEN $2 ELSE last_message_preview END,
    last_message_direction = CASE WHEN last_message_direction IS NULL OR $1 >= last_activity_at THEN 'inbound' ELSE last_message_direction END,
    unread_count = unread_count + 1,
    waiting_since = COALESCE(waiting_since, $1),
    status = CASE WHEN status IN ('pending', 'snoozed') THEN 'open' ELSE status END,
    snoozed_until = CASE WHEN status IN ('pending', 'snoozed') THEN NULL ELSE snoozed_until END,
    updated_at = now()
WHERE id = $3 AND organization_id = $4
`

type TouchConversationInboundParams struct {
	At             pgtype.Timestamptz
	Preview        *string
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

// Un mensaje del cliente: abre la ventana de 24 h, sube los no leídos y reabre lo pendiente o pospuesto.
// Una entrega atrasada (Meta reintenta) nunca hace retroceder la ventana ni la vista previa.
func (q *Queries) TouchConversationInbound(ctx context.Context, arg TouchConversationInboundParams) error {
	_, err := q.db.Exec(ctx, touchConversationInbound,
		arg.At,
		arg.Preview,
		arg.ID,
		arg.OrganizationID,
	)
	return err
}

const touchConversationOutbound = `-- name: TouchConversationOutbound :exec
UPDATE conversations
SET last_activity_at = $1, last_message_preview = $2, last_message_direction = 'outbound',
    first_response_at = COALESCE(first_response_at, $1),
    waiting_since = NULL, updated_at = now()
WHERE id = $3 AND organization_id = $4
`

type TouchConversationOutboundParams struct {
	At             time.Time
	Preview        *string
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

// Una respuesta del equipo: ya no se está esperando al agente.
func (q *Queries) TouchConversationOutbound(ctx context.Context, arg TouchConversationOutboundParams) error {
	_, err := q.db.Exec(ctx, touchConversationOutbound,
		arg.At,
		arg.Preview,
		arg.ID,
		arg.OrganizationID,
	)
	return err
}

const updateConversation = `-- name: UpdateConversation :one
UPDATE conversations
SET status = COALESCE($1::text, status),
    priority = CASE WHEN $2::boolean THEN $3::text ELSE priority END,
    assignee_id = CASE WHEN $4::boolean THEN $5::uuid ELSE assignee_id END,
    handled_by = COALESCE($6::text, handled_by),
    snoozed_until = CASE WHEN $7::boolean THEN $8::timestamptz ELSE snoozed_until END,
    updated_at = now()
WHERE id = $9 AND organization_id = $10
RETURNING id, organization_id, inbox_id, contact_id, display_id, status, priority, assignee_id, handled_by, last_customer_message_at, last_activity_at, last_message_preview, last_message_direction, first_response_at, waiting_since, snoozed_until, unread_count, created_at, updated_at
`

type UpdateConversationParams struct {
	Status         *string
	SetPriority    bool
	Priority       *string
	SetAssignee    bool
	AssigneeID     uuid.NullUUID
	HandledBy      *string
	SetSnoozed     bool
	SnoozedUntil   pgtype.Timestamptz
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

// Cambio parcial de una conversación.
func (q *Queries) UpdateConversation(ctx context.Context, arg UpdateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversation,
		arg.Status,
		arg.SetPriority,
		arg.Priority,
		arg.SetAssignee,
		arg.AssigneeID,
		arg.HandledBy,
		arg.SetSnoozed,
		arg.SnoozedUntil,
		arg.ID,
		arg.OrganizationID,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InboxID,
		&i.ContactID,
		&i.DisplayID,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.HandledBy,
		&i.LastCustomerMessageAt,
		&i.LastActivityAt,
		&i.LastMessagePreview,
		&i.LastMessageDirection,
		&i.FirstResponseAt,
		&i.WaitingSince,
		&i.SnoozedUntil,
		&i.UnreadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWebhookEvent = `-- name: UpsertWebhookEvent :one

INSERT INTO webhook_events (source, event_key, payload) VALUES ($1, $2, $3)
ON CONFLICT (source, event_key) DO UPDATE SET source = webhook_events.source
RETURNING id, processed_at, (xmax = 0) AS inserted
`

type UpsertWebhookEventParams struct {
	Source   string
	EventKey []byte
	Payload  []byte
}

type UpsertWebhookEventRow struct {
	ID          uuid.UUID
	ProcessedAt pgtype.Timestamptz
	Inserted    bool
}

// ---------------------------------------------------------------------------
// Webhooks crudos
// ---------------------------------------------------------------------------
// Registra la entrega o devuelve la ya registrada (misma clave): así se sabe si es nueva o reentrega.
func (q *Queries) UpsertWebhookEvent(ctx context.Context, arg UpsertWebhookEventParams) (UpsertWebhookEventRow, error) {
	row := q.db.QueryRow(ctx, upsertWebhookEvent, arg.Source, arg.EventKey, arg.Payload)
	var i UpsertWebhookEventRow
	err := row.Scan(&i.ID, &i.ProcessedAt, &i.Inserted)
	return i, err
}

const userCanReplyInOrganization = `-- name: UserCanReplyInOrganization :one
SELECT EXISTS (
    SELECT 1 FROM user_organizations uo
    JOIN role_permissions rp ON rp.role_id = uo.role_id AND rp.permission_code = 'org.inbox.reply'
    JOIN users u ON u.id = uo.user_id AND u.is_active
    WHERE uo.user_id = $1 AND uo.organization_id = $2
)
`

type UserCanReplyInOrganizationParams struct {
	UserID         uuid.UUID
	OrganizationID uuid.UUID
}

// ¿Puede este usuario atender conversaciones de la organización? (es miembro y su rol tiene org.inbox.reply,
// o es de la plataforma con acceso a todas). Es lo que se exige a quien se le asigna una conversación.
func (q *Queries) UserCanReplyInOrganization(ctx context.Context, arg UserCanReplyInOrganizationParams) (bool, error) {
	row := q.db.QueryRow(ctx, userCanReplyInOrganization, arg.UserID, arg.OrganizationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
