// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getCustomer = `-- name: GetCustomer :one
SELECT user_id, phone, default_address, created_at, updated_at FROM customers WHERE user_id = $1
`

func (q *Queries) GetCustomer(ctx context.Context, userID uuid.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, userID)
	var i Customer
	err := row.Scan(
		&i.UserID,
		&i.Phone,
		&i.DefaultAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCustomer = `-- name: InsertCustomer :one
INSERT INTO customers (user_id, phone, default_address, created_at, updated_at)
VALUES ($1, $2, $3,
        timezone('utc', now()), timezone('utc', now()))
RETURNING user_id, phone, default_address, created_at, updated_at
`

type InsertCustomerParams struct {
	UserID         uuid.UUID
	Phone          *string
	DefaultAddress *string
}

func (q *Queries) InsertCustomer(ctx context.Context, arg InsertCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, insertCustomer, arg.UserID, arg.Phone, arg.DefaultAddress)
	var i Customer
	err := row.Scan(
		&i.UserID,
		&i.Phone,
		&i.DefaultAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCustomer = `-- name: UpdateCustomer :execrows
UPDATE customers
SET phone = COALESCE($1, phone),
    default_address = COALESCE($2, default_address),
    updated_at = timezone('utc', now())
WHERE user_id = $3
`

type UpdateCustomerParams struct {
	Phone          *string
	DefaultAddress *string
	UserID         uuid.UUID
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCustomer, arg.Phone, arg.DefaultAddress, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
