// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drivers.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getDriverApplication = `-- name: GetDriverApplication :one
SELECT id, full_name, email, phone, vehicle_type, status, created_at, updated_at FROM driver_applications WHERE id = $1
`

func (q *Queries) GetDriverApplication(ctx context.Context, id uuid.UUID) (DriverApplication, error) {
	row := q.db.QueryRow(ctx, getDriverApplication, id)
	var i DriverApplication
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.VehicleType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDriverApplication = `-- name: InsertDriverApplication :one
INSERT INTO driver_applications (id, full_name, email, phone, vehicle_type, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, 'pending',
        timezone('utc', now()), timezone('utc', now()))
RETURNING id, full_name, email, phone, vehicle_type, status, created_at, updated_at
`

type InsertDriverApplicationParams struct {
	ID          uuid.UUID
	FullName    string
	Email       string
	Phone       string
	VehicleType string
}

func (q *Queries) InsertDriverApplication(ctx context.Context, arg InsertDriverApplicationParams) (DriverApplication, error) {
	row := q.db.QueryRow(ctx, insertDriverApplication,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.VehicleType,
	)
	var i DriverApplication
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.VehicleType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDriverApplications = `-- name: ListDriverApplications :many
SELECT id, full_name, email, phone, vehicle_type, status, created_at, updated_at FROM driver_applications
WHERE $1::application_status IS NULL OR status = $1::application_status
ORDER BY created_at, id
`

func (q *Queries) ListDriverApplications(ctx context.Context, status *ApplicationStatus) ([]DriverApplication, error) {
	rows, err := q.db.Query(ctx, listDriverApplications, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DriverApplication{}
	for rows.Next() {
		var i DriverApplication
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.VehicleType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewDriverApplication = `-- name: ReviewDriverApplication :one
UPDATE driver_applications
SET status = $1, updated_at = timezone('utc', now())
WHERE id = $2 AND status = 'pending'
RETURNING id, full_name, email, phone, vehicle_type, status, created_at, updated_at
`

type ReviewDriverApplicationParams struct {
	Status ApplicationStatus
	ID     uuid.UUID
}

// Solo revisa una solicitud pendiente: si otra petición ya la revisó, no devuelve
// filas. Es lo que evita aprobar dos veces en paralelo.
func (q *Queries) ReviewDriverApplication(ctx context.Context, arg ReviewDriverApplicationParams) (DriverApplication, error) {
	row := q.db.QueryRow(ctx, reviewDriverApplication, arg.Status, arg.ID)
	var i DriverApplication
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.VehicleType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
