// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inboxes.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveInbox = `-- name: ArchiveInbox :execrows
UPDATE inboxes SET archived_at = now(), updated_at = now()
WHERE id = $1 AND organization_id = $2 AND archived_at IS NULL
`

type ArchiveInboxParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) ArchiveInbox(ctx context.Context, arg ArchiveInboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveInbox, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActiveInboxes = `-- name: CountActiveInboxes :one
SELECT count(*) FROM inboxes WHERE organization_id = $1 AND archived_at IS NULL
`

func (q *Queries) CountActiveInboxes(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveInboxes, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOrphanWhatsAppAccounts = `-- name: DeleteOrphanWhatsAppAccounts :exec
DELETE FROM whatsapp_accounts a
WHERE a.organization_id = $1
  AND NOT EXISTS (SELECT 1 FROM whatsapp_channels c WHERE c.whatsapp_account_id = a.id)
`

func (q *Queries) DeleteOrphanWhatsAppAccounts(ctx context.Context, organizationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrphanWhatsAppAccounts, organizationID)
	return err
}

const deleteWhatsAppChannel = `-- name: DeleteWhatsAppChannel :exec
DELETE FROM whatsapp_channels WHERE inbox_id = $1 AND organization_id = $2
`

type DeleteWhatsAppChannelParams struct {
	InboxID        uuid.UUID
	OrganizationID uuid.UUID
}

// Desconectar libera el número (phone_number_id es único): se puede volver a conectar.
func (q *Queries) DeleteWhatsAppChannel(ctx context.Context, arg DeleteWhatsAppChannelParams) error {
	_, err := q.db.Exec(ctx, deleteWhatsAppChannel, arg.InboxID, arg.OrganizationID)
	return err
}

const getChannelByPhoneNumberID = `-- name: GetChannelByPhoneNumberID :one
SELECT c.inbox_id, c.organization_id, c.phone_number_id, c.status AS channel_status,
       a.id AS account_id, a.app_secret_enc, o.status AS organization_status
FROM whatsapp_channels c
JOIN whatsapp_accounts a ON a.id = c.whatsapp_account_id
JOIN inboxes i ON i.id = c.inbox_id
JOIN organizations o ON o.id = c.organization_id
WHERE c.phone_number_id = $1 AND i.archived_at IS NULL
`

type GetChannelByPhoneNumberIDRow struct {
	InboxID            uuid.UUID
	OrganizationID     uuid.UUID
	PhoneNumberID      string
	ChannelStatus      string
	AccountID          uuid.UUID
	AppSecretEnc       *string
	OrganizationStatus string
}

// Enrutamiento del webhook: de qué organización y bandeja es un mensaje, por el número al que llegó.
func (q *Queries) GetChannelByPhoneNumberID(ctx context.Context, phoneNumberID string) (GetChannelByPhoneNumberIDRow, error) {
	row := q.db.QueryRow(ctx, getChannelByPhoneNumberID, phoneNumberID)
	var i GetChannelByPhoneNumberIDRow
	err := row.Scan(
		&i.InboxID,
		&i.OrganizationID,
		&i.PhoneNumberID,
		&i.ChannelStatus,
		&i.AccountID,
		&i.AppSecretEnc,
		&i.OrganizationStatus,
	)
	return i, err
}

const getChannelCredentials = `-- name: GetChannelCredentials :one
SELECT c.inbox_id, c.organization_id, c.phone_number_id, c.status AS channel_status,
       a.id AS account_id, a.waba_id, a.access_token_enc, a.app_secret_enc, a.token_status
FROM whatsapp_channels c
JOIN whatsapp_accounts a ON a.id = c.whatsapp_account_id
JOIN inboxes i ON i.id = c.inbox_id
WHERE c.inbox_id = $1 AND c.organization_id = $2 AND i.archived_at IS NULL
`

type GetChannelCredentialsParams struct {
	InboxID        uuid.UUID
	OrganizationID uuid.UUID
}

type GetChannelCredentialsRow struct {
	InboxID        uuid.UUID
	OrganizationID uuid.UUID
	PhoneNumberID  string
	ChannelStatus  string
	AccountID      uuid.UUID
	WabaID         string
	AccessTokenEnc string
	AppSecretEnc   *string
	TokenStatus    string
}

// Lo necesario para hablar con Meta en nombre de una bandeja: el token CIFRADO y la cuenta.
func (q *Queries) GetChannelCredentials(ctx context.Context, arg GetChannelCredentialsParams) (GetChannelCredentialsRow, error) {
	row := q.db.QueryRow(ctx, getChannelCredentials, arg.InboxID, arg.OrganizationID)
	var i GetChannelCredentialsRow
	err := row.Scan(
		&i.InboxID,
		&i.OrganizationID,
		&i.PhoneNumberID,
		&i.ChannelStatus,
		&i.AccountID,
		&i.WabaID,
		&i.AccessTokenEnc,
		&i.AppSecretEnc,
		&i.TokenStatus,
	)
	return i, err
}

const getInbox = `-- name: GetInbox :one
SELECT i.id, i.organization_id, i.name, i.channel_type, i.archived_at, i.created_at, i.updated_at,
       c.phone_number_id, c.display_phone, c.verified_name, c.quality_rating, c.messaging_tier,
       c.status AS channel_status, c.last_checked_at, a.waba_id, a.token_status
FROM inboxes i
LEFT JOIN whatsapp_channels c ON c.inbox_id = i.id
LEFT JOIN whatsapp_accounts a ON a.id = c.whatsapp_account_id
WHERE i.id = $1 AND i.organization_id = $2
`

type GetInboxParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

type GetInboxRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	ChannelType    string
	ArchivedAt     pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
	PhoneNumberID  *string
	DisplayPhone   *string
	VerifiedName   *string
	QualityRating  *string
	MessagingTier  *string
	ChannelStatus  *string
	LastCheckedAt  pgtype.Timestamptz
	WabaID         *string
	TokenStatus    *string
}

func (q *Queries) GetInbox(ctx context.Context, arg GetInboxParams) (GetInboxRow, error) {
	row := q.db.QueryRow(ctx, getInbox, arg.ID, arg.OrganizationID)
	var i GetInboxRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.ChannelType,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumberID,
		&i.DisplayPhone,
		&i.VerifiedName,
		&i.QualityRating,
		&i.MessagingTier,
		&i.ChannelStatus,
		&i.LastCheckedAt,
		&i.WabaID,
		&i.TokenStatus,
	)
	return i, err
}

const insertInbox = `-- name: InsertInbox :one
INSERT INTO inboxes (id, organization_id, name) VALUES ($1, $2, $3)
RETURNING id, organization_id, name, channel_type, archived_at, created_at, updated_at
`

type InsertInboxParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
}

func (q *Queries) InsertInbox(ctx context.Context, arg InsertInboxParams) (Inbox, error) {
	row := q.db.QueryRow(ctx, insertInbox, arg.ID, arg.OrganizationID, arg.Name)
	var i Inbox
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.ChannelType,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWhatsAppAccount = `-- name: InsertWhatsAppAccount :one
INSERT INTO whatsapp_accounts (id, organization_id, waba_id, access_token_enc, app_secret_enc, connected_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, waba_id, access_token_enc, app_secret_enc, token_status, connected_by, created_at, updated_at
`

type InsertWhatsAppAccountParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	WabaID         string
	AccessTokenEnc string
	AppSecretEnc   *string
	ConnectedBy    uuid.NullUUID
}

func (q *Queries) InsertWhatsAppAccount(ctx context.Context, arg InsertWhatsAppAccountParams) (WhatsappAccount, error) {
	row := q.db.QueryRow(ctx, insertWhatsAppAccount,
		arg.ID,
		arg.OrganizationID,
		arg.WabaID,
		arg.AccessTokenEnc,
		arg.AppSecretEnc,
		arg.ConnectedBy,
	)
	var i WhatsappAccount
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WabaID,
		&i.AccessTokenEnc,
		&i.AppSecretEnc,
		&i.TokenStatus,
		&i.ConnectedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWhatsAppChannel = `-- name: InsertWhatsAppChannel :one
INSERT INTO whatsapp_channels (inbox_id, organization_id, whatsapp_account_id, phone_number_id, display_phone,
                               verified_name, quality_rating, messaging_tier, status, last_checked_at)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, 'connected', now())
RETURNING inbox_id, organization_id, whatsapp_account_id, phone_number_id, display_phone, verified_name, quality_rating, messaging_tier, status, last_checked_at, created_at, updated_at
`

type InsertWhatsAppChannelParams struct {
	InboxID           uuid.UUID
	OrganizationID    uuid.UUID
	WhatsappAccountID uuid.UUID
	PhoneNumberID     string
	DisplayPhone      string
	VerifiedName      *string
	QualityRating     *string
	MessagingTier     *string
}

func (q *Queries) InsertWhatsAppChannel(ctx context.Context, arg InsertWhatsAppChannelParams) (WhatsappChannel, error) {
	row := q.db.QueryRow(ctx, insertWhatsAppChannel,
		arg.InboxID,
		arg.OrganizationID,
		arg.WhatsappAccountID,
		arg.PhoneNumberID,
		arg.DisplayPhone,
		arg.VerifiedName,
		arg.QualityRating,
		arg.MessagingTier,
	)
	var i WhatsappChannel
	err := row.Scan(
		&i.InboxID,
		&i.OrganizationID,
		&i.WhatsappAccountID,
		&i.PhoneNumberID,
		&i.DisplayPhone,
		&i.VerifiedName,
		&i.QualityRating,
		&i.MessagingTier,
		&i.Status,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInboxes = `-- name: ListInboxes :many
SELECT i.id, i.organization_id, i.name, i.channel_type, i.archived_at, i.created_at, i.updated_at,
       c.phone_number_id, c.display_phone, c.verified_name, c.quality_rating, c.messaging_tier,
       c.status AS channel_status, c.last_checked_at, a.waba_id, a.token_status
FROM inboxes i
LEFT JOIN whatsapp_channels c ON c.inbox_id = i.id
LEFT JOIN whatsapp_accounts a ON a.id = c.whatsapp_account_id
WHERE i.organization_id = $1
  AND ($2::boolean OR i.archived_at IS NULL)
ORDER BY i.name, i.id
`

type ListInboxesParams struct {
	OrganizationID  uuid.UUID
	IncludeArchived bool
}

type ListInboxesRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	ChannelType    string
	ArchivedAt     pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
	PhoneNumberID  *string
	DisplayPhone   *string
	VerifiedName   *string
	QualityRating  *string
	MessagingTier  *string
	ChannelStatus  *string
	LastCheckedAt  pgtype.Timestamptz
	WabaID         *string
	TokenStatus    *string
}

// Bandeja con su número y su cuenta, SIN secretos.
func (q *Queries) ListInboxes(ctx context.Context, arg ListInboxesParams) ([]ListInboxesRow, error) {
	rows, err := q.db.Query(ctx, listInboxes, arg.OrganizationID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInboxesRow{}
	for rows.Next() {
		var i ListInboxesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.ChannelType,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PhoneNumberID,
			&i.DisplayPhone,
			&i.VerifiedName,
			&i.QualityRating,
			&i.MessagingTier,
			&i.ChannelStatus,
			&i.LastCheckedAt,
			&i.WabaID,
			&i.TokenStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshChannelInfo = `-- name: RefreshChannelInfo :exec
UPDATE whatsapp_channels
SET display_phone = $1, verified_name = $2,
    quality_rating = $3, messaging_tier = $4,
    status = 'connected', last_checked_at = now(), updated_at = now()
WHERE inbox_id = $5 AND organization_id = $6
`

type RefreshChannelInfoParams struct {
	DisplayPhone   string
	VerifiedName   *string
	QualityRating  *string
	MessagingTier  *string
	InboxID        uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) RefreshChannelInfo(ctx context.Context, arg RefreshChannelInfoParams) error {
	_, err := q.db.Exec(ctx, refreshChannelInfo,
		arg.DisplayPhone,
		arg.VerifiedName,
		arg.QualityRating,
		arg.MessagingTier,
		arg.InboxID,
		arg.OrganizationID,
	)
	return err
}

const renameInbox = `-- name: RenameInbox :one
UPDATE inboxes SET name = $1, updated_at = now()
WHERE id = $2 AND organization_id = $3 AND archived_at IS NULL
RETURNING id, organization_id, name, channel_type, archived_at, created_at, updated_at
`

type RenameInboxParams struct {
	Name           string
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) RenameInbox(ctx context.Context, arg RenameInboxParams) (Inbox, error) {
	row := q.db.QueryRow(ctx, renameInbox, arg.Name, arg.ID, arg.OrganizationID)
	var i Inbox
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.ChannelType,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setAccountTokenStatus = `-- name: SetAccountTokenStatus :exec
UPDATE whatsapp_accounts SET token_status = $1, updated_at = now()
WHERE id = $2 AND organization_id = $3
`

type SetAccountTokenStatusParams struct {
	TokenStatus    string
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) SetAccountTokenStatus(ctx context.Context, arg SetAccountTokenStatusParams) error {
	_, err := q.db.Exec(ctx, setAccountTokenStatus, arg.TokenStatus, arg.ID, arg.OrganizationID)
	return err
}

const setChannelStatus = `-- name: SetChannelStatus :exec
UPDATE whatsapp_channels SET status = $1, updated_at = now()
WHERE inbox_id = $2 AND organization_id = $3
`

type SetChannelStatusParams struct {
	Status         string
	InboxID        uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) SetChannelStatus(ctx context.Context, arg SetChannelStatusParams) error {
	_, err := q.db.Exec(ctx, setChannelStatus, arg.Status, arg.InboxID, arg.OrganizationID)
	return err
}

const updateAccountToken = `-- name: UpdateAccountToken :exec
UPDATE whatsapp_accounts
SET access_token_enc = $1, token_status = 'valid', updated_at = now()
WHERE id = $2 AND organization_id = $3
`

type UpdateAccountTokenParams struct {
	AccessTokenEnc string
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) UpdateAccountToken(ctx context.Context, arg UpdateAccountTokenParams) error {
	_, err := q.db.Exec(ctx, updateAccountToken, arg.AccessTokenEnc, arg.ID, arg.OrganizationID)
	return err
}
