// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :execrows
UPDATE organization_invitations SET accepted_at = now(), accepted_by = $1
WHERE id = $2 AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at > now()
`

type AcceptInvitationParams struct {
	AcceptedBy uuid.NullUUID
	ID         uuid.UUID
}

func (q *Queries) AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptInvitation, arg.AcceptedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countPendingInvitations = `-- name: CountPendingInvitations :one
SELECT count(*) FROM organization_invitations
WHERE organization_id = $1 AND accepted_at IS NULL AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) CountPendingInvitations(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingInvitations, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getInvitation = `-- name: GetInvitation :one
SELECT i.id, i.organization_id, i.email, i.role_id, i.token_hash, i.invited_by, i.created_at, i.expires_at, i.accepted_at, i.accepted_by, i.revoked_at, r.code AS role_code, r.name AS role_name
FROM organization_invitations i JOIN roles r ON r.id = i.role_id
WHERE i.id = $1 AND i.organization_id = $2
`

type GetInvitationParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

type GetInvitationRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Email          string
	RoleID         uuid.UUID
	TokenHash      []byte
	InvitedBy      uuid.NullUUID
	CreatedAt      time.Time
	ExpiresAt      time.Time
	AcceptedAt     pgtype.Timestamptz
	AcceptedBy     uuid.NullUUID
	RevokedAt      pgtype.Timestamptz
	RoleCode       string
	RoleName       string
}

func (q *Queries) GetInvitation(ctx context.Context, arg GetInvitationParams) (GetInvitationRow, error) {
	row := q.db.QueryRow(ctx, getInvitation, arg.ID, arg.OrganizationID)
	var i GetInvitationRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.RoleID,
		&i.TokenHash,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.RoleCode,
		&i.RoleName,
	)
	return i, err
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT i.id, i.organization_id, i.email, i.role_id, i.token_hash, i.invited_by, i.created_at, i.expires_at, i.accepted_at, i.accepted_by, i.revoked_at, r.code AS role_code, r.name AS role_name, o.name AS organization_name,
       o.slug AS organization_slug, o.status AS organization_status
FROM organization_invitations i
JOIN roles r ON r.id = i.role_id
JOIN organizations o ON o.id = i.organization_id
WHERE i.token_hash = $1
`

type GetInvitationByTokenHashRow struct {
	ID                 uuid.UUID
	OrganizationID     uuid.UUID
	Email              string
	RoleID             uuid.UUID
	TokenHash          []byte
	InvitedBy          uuid.NullUUID
	CreatedAt          time.Time
	ExpiresAt          time.Time
	AcceptedAt         pgtype.Timestamptz
	AcceptedBy         uuid.NullUUID
	RevokedAt          pgtype.Timestamptz
	RoleCode           string
	RoleName           string
	OrganizationName   string
	OrganizationSlug   string
	OrganizationStatus string
}

// El token se busca por su hash. La invitación solo es utilizable si sigue pendiente
// y vigente; el servicio lo comprueba con la fila completa.
func (q *Queries) GetInvitationByTokenHash(ctx context.Context, tokenHash []byte) (GetInvitationByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHash, tokenHash)
	var i GetInvitationByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.RoleID,
		&i.TokenHash,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.RoleCode,
		&i.RoleName,
		&i.OrganizationName,
		&i.OrganizationSlug,
		&i.OrganizationStatus,
	)
	return i, err
}

const getInvitationByTokenHashForUpdate = `-- name: GetInvitationByTokenHashForUpdate :one
SELECT id, organization_id, email, role_id, token_hash, invited_by, created_at, expires_at, accepted_at, accepted_by, revoked_at FROM organization_invitations WHERE token_hash = $1 FOR UPDATE
`

func (q *Queries) GetInvitationByTokenHashForUpdate(ctx context.Context, tokenHash []byte) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHashForUpdate, tokenHash)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.RoleID,
		&i.TokenHash,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
	)
	return i, err
}

const listPendingInvitations = `-- name: ListPendingInvitations :many
SELECT i.id, i.organization_id, i.email, i.role_id, i.token_hash, i.invited_by, i.created_at, i.expires_at, i.accepted_at, i.accepted_by, i.revoked_at, r.code AS role_code, r.name AS role_name
FROM organization_invitations i JOIN roles r ON r.id = i.role_id
WHERE i.organization_id = $1 AND i.accepted_at IS NULL AND i.revoked_at IS NULL
ORDER BY i.created_at DESC, i.id
`

type ListPendingInvitationsRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Email          string
	RoleID         uuid.UUID
	TokenHash      []byte
	InvitedBy      uuid.NullUUID
	CreatedAt      time.Time
	ExpiresAt      time.Time
	AcceptedAt     pgtype.Timestamptz
	AcceptedBy     uuid.NullUUID
	RevokedAt      pgtype.Timestamptz
	RoleCode       string
	RoleName       string
}

func (q *Queries) ListPendingInvitations(ctx context.Context, organizationID uuid.UUID) ([]ListPendingInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listPendingInvitations, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingInvitationsRow{}
	for rows.Next() {
		var i ListPendingInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.RoleID,
			&i.TokenHash,
			&i.InvitedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedBy,
			&i.RevokedAt,
			&i.RoleCode,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingInvitationExists = `-- name: PendingInvitationExists :one
SELECT EXISTS (
    SELECT 1 FROM organization_invitations
    WHERE organization_id = $1 AND email = $2
      AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at > now())
`

type PendingInvitationExistsParams struct {
	OrganizationID uuid.UUID
	Email          string
}

// Solo cuenta la que aún vale: una caducada no ocupa lugar y reinvitar la reemplaza.
func (q *Queries) PendingInvitationExists(ctx context.Context, arg PendingInvitationExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, pendingInvitationExists, arg.OrganizationID, arg.Email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const revokeInvitation = `-- name: RevokeInvitation :execrows
UPDATE organization_invitations SET revoked_at = now()
WHERE id = $1 AND organization_id = $2
  AND accepted_at IS NULL AND revoked_at IS NULL
`

type RevokeInvitationParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvitation, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertInvitation = `-- name: UpsertInvitation :one
INSERT INTO organization_invitations (organization_id, email, role_id, token_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (organization_id, email) WHERE accepted_at IS NULL AND revoked_at IS NULL
DO UPDATE SET role_id = EXCLUDED.role_id, token_hash = EXCLUDED.token_hash,
              invited_by = EXCLUDED.invited_by, expires_at = EXCLUDED.expires_at,
              created_at = now()
RETURNING id, organization_id, email, role_id, token_hash, invited_by, created_at, expires_at, accepted_at, accepted_by, revoked_at
`

type UpsertInvitationParams struct {
	OrganizationID uuid.UUID
	Email          string
	RoleID         uuid.UUID
	TokenHash      []byte
	InvitedBy      uuid.NullUUID
	ExpiresAt      time.Time
}

// Reinvitar a un correo con invitación pendiente la REEMPLAZA (nuevo token, nueva
// vigencia, nuevo rol): así "reenviar" no deja dos enlaces vivos.
func (q *Queries) UpsertInvitation(ctx context.Context, arg UpsertInvitationParams) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, upsertInvitation,
		arg.OrganizationID,
		arg.Email,
		arg.RoleID,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.RoleID,
		&i.TokenHash,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
	)
	return i, err
}
