// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApplicationStatus string

const (
	ApplicationStatusPending  ApplicationStatus = "pending"
	ApplicationStatusApproved ApplicationStatus = "approved"
	ApplicationStatusRejected ApplicationStatus = "rejected"
)

func (e *ApplicationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApplicationStatus(s)
	case string:
		*e = ApplicationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ApplicationStatus: %T", src)
	}
	return nil
}

type NullApplicationStatus struct {
	ApplicationStatus ApplicationStatus
	Valid             bool // Valid is true if ApplicationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApplicationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ApplicationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApplicationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApplicationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApplicationStatus), nil
}

type AuditLog struct {
	ID             uuid.UUID
	ActorID        uuid.NullUUID
	Action         string
	TargetUserID   uuid.NullUUID
	OrganizationID uuid.NullUUID
	RoleID         uuid.NullUUID
	RoleCode       *string
	Detail         []byte
	CreatedAt      time.Time
}

type AuthUser struct {
	ID uuid.UUID
}

type Category struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Position       int32
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Contact struct {
	ID               uuid.UUID
	OrganizationID   uuid.UUID
	PhoneE164        string
	Name             *string
	Email            *string
	CustomerUserID   uuid.NullUUID
	CustomAttributes []byte
	Blocked          bool
	Source           string
	LastActivityAt   pgtype.Timestamptz
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Conversation struct {
	ID                    uuid.UUID
	OrganizationID        uuid.UUID
	InboxID               uuid.UUID
	ContactID             uuid.UUID
	DisplayID             int64
	Status                string
	Priority              *string
	AssigneeID            uuid.NullUUID
	HandledBy             string
	LastCustomerMessageAt pgtype.Timestamptz
	LastActivityAt        time.Time
	LastMessagePreview    *string
	LastMessageDirection  *string
	FirstResponseAt       pgtype.Timestamptz
	WaitingSince          pgtype.Timestamptz
	SnoozedUntil          pgtype.Timestamptz
	UnreadCount           int32
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type Customer struct {
	UserID         uuid.UUID
	Phone          *string
	DefaultAddress *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type DriverApplication struct {
	ID          uuid.UUID
	FullName    string
	Email       string
	Phone       string
	VehicleType string
	Status      ApplicationStatus
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Inbox struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	ChannelType    string
	ArchivedAt     pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Message struct {
	ID               uuid.UUID
	OrganizationID   uuid.UUID
	ConversationID   uuid.UUID
	InboxID          uuid.UUID
	Direction        string
	Kind             string
	Body             *string
	Wamid            *string
	Status           string
	ErrorCode        *string
	ErrorDetail      *string
	Attempts         int32
	NextAttemptAt    pgtype.Timestamptz
	LockedUntil      pgtype.Timestamptz
	SentAt           pgtype.Timestamptz
	DeliveredAt      pgtype.Timestamptz
	ReadAt           pgtype.Timestamptz
	FailedAt         pgtype.Timestamptz
	SenderUserID     uuid.NullUUID
	ReplyToMessageID uuid.NullUUID
	Payload          []byte
	PricingCategory  *string
	Billable         *bool
	CreatedAt        time.Time
}

type MessageAttachment struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	MessageID      uuid.UUID
	Kind           string
	MimeType       *string
	Filename       *string
	SizeBytes      *int64
	Sha256         *string
	WaMediaID      *string
	Caption        *string
	CreatedAt      time.Time
}

type ModifierGroup struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	SelectionType  string
	MinSelect      int32
	MaxSelect      int32
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ModifierOption struct {
	ID              uuid.UUID
	ModifierGroupID uuid.UUID
	OrganizationID  uuid.UUID
	Name            string
	PriceDeltaCents int32
	IsActive        bool
	Position        int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Order struct {
	ID               uuid.UUID
	OrganizationID   uuid.UUID
	CustomerID       uuid.UUID
	Status           string
	SubtotalCents    int32
	DiscountCents    int32
	DeliveryFeeCents int32
	TotalCents       int32
	PlacedAt         pgtype.Timestamptz
	StatusChangedAt  pgtype.Timestamptz
	CreatedAt        time.Time
	UpdatedAt        time.Time
	PromotionID      uuid.NullUUID
}

type OrderItem struct {
	ID                     uuid.UUID
	OrderID                uuid.UUID
	OrganizationID         uuid.UUID
	ProductVariantID       uuid.NullUUID
	NameSnapshot           string
	UnitPriceCentsSnapshot int32
	ModifiersSnapshot      []byte
	UnitTotalCents         int32
	Quantity               int32
	LineTotalCents         int32
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

type Organization struct {
	ID              uuid.UUID
	Name            string
	Description     *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Slug            string
	PlanTier        string
	Status          string
	StatusReason    *string
	StatusChangedAt pgtype.Timestamptz
}

type OrganizationCounter struct {
	OrganizationID  uuid.UUID
	ConversationSeq int64
}

type OrganizationFeatureOverride struct {
	OrganizationID uuid.UUID
	Feature        string
	Enabled        bool
	Reason         *string
	CreatedBy      uuid.NullUUID
	CreatedAt      time.Time
}

type OrganizationInvitation struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Email          string
	RoleID         uuid.UUID
	TokenHash      []byte
	InvitedBy      uuid.NullUUID
	CreatedAt      time.Time
	ExpiresAt      time.Time
	AcceptedAt     pgtype.Timestamptz
	AcceptedBy     uuid.NullUUID
	RevokedAt      pgtype.Timestamptz
}

type OrganizationSetting struct {
	OrganizationID uuid.UUID
	LegalName      *string
	TaxID          *string
	ContactEmail   *string
	ContactPhone   *string
	Address        *string
	City           *string
	LogoUrl        *string
	Timezone       string
	Locale         string
	Currency       string
	BusinessHours  []byte
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type OrganizationSubscription struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	PlanTier       string
	StartedAt      time.Time
	EndedAt        pgtype.Timestamptz
	ChangedBy      uuid.NullUUID
	Reason         *string
}

type Payment struct {
	ID             uuid.UUID
	OrderID        uuid.UUID
	OrganizationID uuid.UUID
	Status         string
	AmountCents    int32
	Currency       string
	Gateway        string
	CheckoutUrl    *string
	FailureReason  *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type PaymentEvent struct {
	ID         uuid.UUID
	Source     string
	EventKey   string
	Payload    []byte
	ReceivedAt time.Time
}

type Permission struct {
	Code        string
	Scope       string
	Description string
	Delegable   bool
}

type Product struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	CategoryID     uuid.NullUUID
	Name           string
	Description    *string
	ImageUrl       *string
	Position       int32
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Ingredients    []string
	Channels       []string
}

type ProductModifierGroup struct {
	ProductID       uuid.UUID
	OrganizationID  uuid.UUID
	ModifierGroupID uuid.UUID
	Position        int32
}

type ProductVariant struct {
	ID             uuid.UUID
	ProductID      uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	PriceCents     int32
	IsDefault      bool
	IsActive       bool
	Position       int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Promotion struct {
	ID               uuid.UUID
	OrganizationID   uuid.UUID
	Code             string
	DiscountType     string
	Value            int32
	MinOrderCents    int32
	StartsAt         pgtype.Timestamptz
	EndsAt           pgtype.Timestamptz
	MaxUses          *int32
	PerCustomerLimit *int32
	IsActive         bool
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type PromotionRedemption struct {
	ID             uuid.UUID
	PromotionID    uuid.UUID
	OrganizationID uuid.UUID
	OrderID        uuid.UUID
	CustomerID     uuid.UUID
	DiscountCents  int32
	AppliedAt      time.Time
}

type Role struct {
	ID             uuid.UUID
	Code           string
	Name           string
	Description    *string
	Scope          string
	OrganizationID uuid.NullUUID
	IsSystem       bool
	OrgAssignable  bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type RolePermission struct {
	RoleID         uuid.UUID
	PermissionCode string
}

type UnmatchedStatus struct {
	ID              uuid.UUID
	Wamid           string
	Status          string
	OccurredAt      time.Time
	ErrorCode       *string
	ErrorDetail     *string
	PricingCategory *string
	Billable        *bool
	CreatedAt       time.Time
}

type User struct {
	ID        uuid.UUID
	Email     string
	FullName  *string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserOrganization struct {
	UserID         uuid.UUID
	OrganizationID uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	RoleID         uuid.UUID
}

type UserPlatformRole struct {
	UserID    uuid.UUID
	RoleID    uuid.UUID
	GrantedBy uuid.NullUUID
	CreatedAt time.Time
}

type WebhookEvent struct {
	ID          uuid.UUID
	Source      string
	EventKey    []byte
	ReceivedAt  time.Time
	ProcessedAt pgtype.Timestamptz
	Error       *string
	Payload     []byte
}

type WhatsappAccount struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	WabaID         string
	AccessTokenEnc string
	AppSecretEnc   *string
	TokenStatus    string
	ConnectedBy    uuid.NullUUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type WhatsappChannel struct {
	InboxID           uuid.UUID
	OrganizationID    uuid.UUID
	WhatsappAccountID uuid.UUID
	PhoneNumberID     string
	DisplayPhone      string
	VerifiedName      *string
	QualityRating     *string
	MessagingTier     *string
	Status            string
	LastCheckedAt     pgtype.Timestamptz
	CreatedAt         time.Time
	UpdatedAt         time.Time
}
