// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const applyPromotionToOrder = `-- name: ApplyPromotionToOrder :one
UPDATE orders
SET promotion_id = $1, discount_cents = $2, total_cents = $3, updated_at = now()
WHERE id = $4 AND organization_id = $5 AND status = 'draft'
RETURNING id, organization_id, customer_id, status, subtotal_cents, discount_cents, delivery_fee_cents, total_cents, placed_at, status_changed_at, created_at, updated_at, promotion_id, subtotal_local_cents, platform_fee_cents, courier_fee_cents, pricing_snapshot
`

type ApplyPromotionToOrderParams struct {
	PromotionID    uuid.NullUUID
	DiscountCents  int32
	TotalCents     int32
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

// Solo mientras el pedido sigue en 'draft' (lo exige el servicio, no esta consulta). total_cents
// ya viene calculado desde Go, mismo motivo que SetOrderAmounts.
func (q *Queries) ApplyPromotionToOrder(ctx context.Context, arg ApplyPromotionToOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, applyPromotionToOrder,
		arg.PromotionID,
		arg.DiscountCents,
		arg.TotalCents,
		arg.ID,
		arg.OrganizationID,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CustomerID,
		&i.Status,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.DeliveryFeeCents,
		&i.TotalCents,
		&i.PlacedAt,
		&i.StatusChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PromotionID,
		&i.SubtotalLocalCents,
		&i.PlatformFeeCents,
		&i.CourierFeeCents,
		&i.PricingSnapshot,
	)
	return i, err
}

const countOrdersByCustomer = `-- name: CountOrdersByCustomer :one
SELECT count(*) FROM orders WHERE customer_id = $1 AND status <> 'draft'
`

func (q *Queries) CountOrdersByCustomer(ctx context.Context, customerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByCustomer, customerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrdersByOrganization = `-- name: CountOrdersByOrganization :one
SELECT count(*) FROM orders
WHERE organization_id = $1
  AND ($2::text IS NULL OR status = $2)
`

type CountOrdersByOrganizationParams struct {
	OrganizationID uuid.UUID
	Status         *string
}

func (q *Queries) CountOrdersByOrganization(ctx context.Context, arg CountOrdersByOrganizationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByOrganization, arg.OrganizationID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOrderItem = `-- name: DeleteOrderItem :execrows
DELETE FROM order_items WHERE id = $1 AND order_id = $2 AND organization_id = $3
`

type DeleteOrderItemParams struct {
	ID             uuid.UUID
	OrderID        uuid.UUID
	OrganizationID uuid.UUID
}

// Solo se llama mientras el pedido sigue en 'draft' (lo exige el servicio, no esta consulta).
func (q *Queries) DeleteOrderItem(ctx context.Context, arg DeleteOrderItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrderItem, arg.ID, arg.OrderID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrCreateDraftOrder = `-- name: GetOrCreateDraftOrder :one

INSERT INTO orders (organization_id, customer_id)
VALUES ($1, $2)
ON CONFLICT (organization_id, customer_id) WHERE status = 'draft'
DO UPDATE SET updated_at = orders.updated_at
RETURNING id, organization_id, customer_id, status, subtotal_cents, discount_cents, delivery_fee_cents, total_cents, placed_at, status_changed_at, created_at, updated_at, promotion_id, subtotal_local_cents, platform_fee_cents, courier_fee_cents, pricing_snapshot
`

type GetOrCreateDraftOrderParams struct {
	OrganizationID uuid.UUID
	CustomerID     uuid.UUID
}

// ---------------------------------------------------------------------------
// Pedidos
// ---------------------------------------------------------------------------
// Ver el carrito y crearlo si no existe son la misma operación: el índice único parcial
// (organization_id, customer_id) WHERE status = 'draft' hace que un segundo intento devuelva el
// MISMO carrito en vez de chocar. En cuanto el pedido deja 'draft', el índice deja de aplicarle:
// la siguiente vez que este cliente compre en esta organización, se abre un carrito nuevo.
func (q *Queries) GetOrCreateDraftOrder(ctx context.Context, arg GetOrCreateDraftOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrCreateDraftOrder, arg.OrganizationID, arg.CustomerID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CustomerID,
		&i.Status,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.DeliveryFeeCents,
		&i.TotalCents,
		&i.PlacedAt,
		&i.StatusChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PromotionID,
		&i.SubtotalLocalCents,
		&i.PlatformFeeCents,
		&i.CourierFeeCents,
		&i.PricingSnapshot,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, organization_id, customer_id, status, subtotal_cents, discount_cents, delivery_fee_cents, total_cents, placed_at, status_changed_at, created_at, updated_at, promotion_id, subtotal_local_cents, platform_fee_cents, courier_fee_cents, pricing_snapshot FROM orders WHERE id = $1 AND organization_id = $2
`

type GetOrderParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) GetOrder(ctx context.Context, arg GetOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, arg.ID, arg.OrganizationID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CustomerID,
		&i.Status,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.DeliveryFeeCents,
		&i.TotalCents,
		&i.PlacedAt,
		&i.StatusChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PromotionID,
		&i.SubtotalLocalCents,
		&i.PlatformFeeCents,
		&i.CourierFeeCents,
		&i.PricingSnapshot,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, organization_id, customer_id, status, subtotal_cents, discount_cents, delivery_fee_cents, total_cents, placed_at, status_changed_at, created_at, updated_at, promotion_id, subtotal_local_cents, platform_fee_cents, courier_fee_cents, pricing_snapshot FROM orders WHERE id = $1
`

// Sin organization_id: la usa el cliente para ver/cancelar UNO de sus propios pedidos por
// /v1/orders/{id}, sin tener que conocer (ni declarar) de qué organización es. Segura porque el
// id es un UUID no adivinable y el servicio comprueba dueño (customer_id) justo después.
func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CustomerID,
		&i.Status,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.DeliveryFeeCents,
		&i.TotalCents,
		&i.PlacedAt,
		&i.StatusChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PromotionID,
		&i.SubtotalLocalCents,
		&i.PlatformFeeCents,
		&i.CourierFeeCents,
		&i.PricingSnapshot,
	)
	return i, err
}

const getOrderItem = `-- name: GetOrderItem :one
SELECT id, order_id, organization_id, product_variant_id, name_snapshot, unit_price_cents_snapshot, modifiers_snapshot, unit_total_cents, quantity, line_total_cents, created_at, updated_at, unit_local_total_cents, platform_fee_bps FROM order_items WHERE id = $1 AND order_id = $2 AND organization_id = $3
`

type GetOrderItemParams struct {
	ID             uuid.UUID
	OrderID        uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) GetOrderItem(ctx context.Context, arg GetOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, getOrderItem, arg.ID, arg.OrderID, arg.OrganizationID)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.OrganizationID,
		&i.ProductVariantID,
		&i.NameSnapshot,
		&i.UnitPriceCentsSnapshot,
		&i.ModifiersSnapshot,
		&i.UnitTotalCents,
		&i.Quantity,
		&i.LineTotalCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UnitLocalTotalCents,
		&i.PlatformFeeBps,
	)
	return i, err
}

const insertOrderItem = `-- name: InsertOrderItem :one

INSERT INTO order_items (
    order_id, organization_id, product_variant_id, name_snapshot,
    unit_price_cents_snapshot, modifiers_snapshot, unit_total_cents, quantity, line_total_cents,
    unit_local_total_cents, platform_fee_bps
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9,
    $10, $11
)
RETURNING id, order_id, organization_id, product_variant_id, name_snapshot, unit_price_cents_snapshot, modifiers_snapshot, unit_total_cents, quantity, line_total_cents, created_at, updated_at, unit_local_total_cents, platform_fee_bps
`

type InsertOrderItemParams struct {
	OrderID                uuid.UUID
	OrganizationID         uuid.UUID
	ProductVariantID       uuid.NullUUID
	NameSnapshot           string
	UnitPriceCentsSnapshot int32
	ModifiersSnapshot      []byte
	UnitTotalCents         int32
	Quantity               int32
	LineTotalCents         int32
	UnitLocalTotalCents    int32
	PlatformFeeBps         int32
}

// ---------------------------------------------------------------------------
// Líneas del pedido (carrito)
// ---------------------------------------------------------------------------
func (q *Queries) InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, insertOrderItem,
		arg.OrderID,
		arg.OrganizationID,
		arg.ProductVariantID,
		arg.NameSnapshot,
		arg.UnitPriceCentsSnapshot,
		arg.ModifiersSnapshot,
		arg.UnitTotalCents,
		arg.Quantity,
		arg.LineTotalCents,
		arg.UnitLocalTotalCents,
		arg.PlatformFeeBps,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.OrganizationID,
		&i.ProductVariantID,
		&i.NameSnapshot,
		&i.UnitPriceCentsSnapshot,
		&i.ModifiersSnapshot,
		&i.UnitTotalCents,
		&i.Quantity,
		&i.LineTotalCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UnitLocalTotalCents,
		&i.PlatformFeeBps,
	)
	return i, err
}

const listMyDraftOrders = `-- name: ListMyDraftOrders :many
SELECT o.id, o.organization_id, org.name AS organization_name, org.slug AS organization_slug,
       o.total_cents, o.updated_at,
       (SELECT count(*) FROM order_items oi WHERE oi.order_id = o.id)::int AS item_count
FROM orders o
JOIN organizations org ON org.id = o.organization_id
WHERE o.customer_id = $1 AND o.status = 'draft'
  AND EXISTS (SELECT 1 FROM order_items oi WHERE oi.order_id = o.id)
ORDER BY o.updated_at DESC, o.id
`

type ListMyDraftOrdersRow struct {
	ID               uuid.UUID
	OrganizationID   uuid.UUID
	OrganizationName string
	OrganizationSlug string
	TotalCents       int32
	UpdatedAt        time.Time
	ItemCount        int32
}

// "Mis carritos": los borradores abiertos del cliente, cruzando organizaciones a propósito —
// mismo motivo que ListOrdersByCustomer, pero al revés (status = 'draft'). Sin paginar: un
// cliente tiene a lo sumo un puñado de carritos abiertos a la vez (uno por restaurante). Excluye
// los vacíos (EXISTS): abrir el menú de un restaurante crea un borrador aunque todavía no se
// agregue nada — eso no es un carrito que mostrar en "todas las rutas".
func (q *Queries) ListMyDraftOrders(ctx context.Context, customerID uuid.UUID) ([]ListMyDraftOrdersRow, error) {
	rows, err := q.db.Query(ctx, listMyDraftOrders, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyDraftOrdersRow{}
	for rows.Next() {
		var i ListMyDraftOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.OrganizationSlug,
			&i.TotalCents,
			&i.UpdatedAt,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsByOrder = `-- name: ListOrderItemsByOrder :many
SELECT id, order_id, organization_id, product_variant_id, name_snapshot, unit_price_cents_snapshot, modifiers_snapshot, unit_total_cents, quantity, line_total_cents, created_at, updated_at, unit_local_total_cents, platform_fee_bps FROM order_items WHERE order_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListOrderItemsByOrder(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.OrganizationID,
			&i.ProductVariantID,
			&i.NameSnapshot,
			&i.UnitPriceCentsSnapshot,
			&i.ModifiersSnapshot,
			&i.UnitTotalCents,
			&i.Quantity,
			&i.LineTotalCents,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UnitLocalTotalCents,
			&i.PlatformFeeBps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByCustomer = `-- name: ListOrdersByCustomer :many
SELECT id, organization_id, customer_id, status, subtotal_cents, discount_cents, delivery_fee_cents, total_cents, placed_at, status_changed_at, created_at, updated_at, promotion_id, subtotal_local_cents, platform_fee_cents, courier_fee_cents, pricing_snapshot FROM orders WHERE customer_id = $1 AND status <> 'draft'
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListOrdersByCustomerParams struct {
	CustomerID uuid.UUID
	PageOffset int32
	PageSize   int32
}

// Cruza organizaciones a propósito: es "mis pedidos" del cliente, no el de un negocio.
func (q *Queries) ListOrdersByCustomer(ctx context.Context, arg ListOrdersByCustomerParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByCustomer, arg.CustomerID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CustomerID,
			&i.Status,
			&i.SubtotalCents,
			&i.DiscountCents,
			&i.DeliveryFeeCents,
			&i.TotalCents,
			&i.PlacedAt,
			&i.StatusChangedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PromotionID,
			&i.SubtotalLocalCents,
			&i.PlatformFeeCents,
			&i.CourierFeeCents,
			&i.PricingSnapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByOrganization = `-- name: ListOrdersByOrganization :many
SELECT id, organization_id, customer_id, status, subtotal_cents, discount_cents, delivery_fee_cents, total_cents, placed_at, status_changed_at, created_at, updated_at, promotion_id, subtotal_local_cents, platform_fee_cents, courier_fee_cents, pricing_snapshot FROM orders
WHERE organization_id = $1
  AND ($2::text IS NULL OR status = $2)
ORDER BY created_at DESC, id DESC
LIMIT $4 OFFSET $3
`

type ListOrdersByOrganizationParams struct {
	OrganizationID uuid.UUID
	Status         *string
	PageOffset     int32
	PageSize       int32
}

func (q *Queries) ListOrdersByOrganization(ctx context.Context, arg ListOrdersByOrganizationParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByOrganization,
		arg.OrganizationID,
		arg.Status,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CustomerID,
			&i.Status,
			&i.SubtotalCents,
			&i.DiscountCents,
			&i.DeliveryFeeCents,
			&i.TotalCents,
			&i.PlacedAt,
			&i.StatusChangedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PromotionID,
			&i.SubtotalLocalCents,
			&i.PlatformFeeCents,
			&i.CourierFeeCents,
			&i.PricingSnapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recalcCartAmounts = `-- name: RecalcCartAmounts :one
UPDATE orders
SET subtotal_cents = $1, discount_cents = 0, promotion_id = NULL,
    delivery_fee_cents = $2, total_cents = $3, updated_at = now()
WHERE id = $4 AND organization_id = $5
RETURNING id, organization_id, customer_id, status, subtotal_cents, discount_cents, delivery_fee_cents, total_cents, placed_at, status_changed_at, created_at, updated_at, promotion_id, subtotal_local_cents, platform_fee_cents, courier_fee_cents, pricing_snapshot
`

type RecalcCartAmountsParams struct {
	SubtotalCents    int32
	DeliveryFeeCents int32
	TotalCents       int32
	ID               uuid.UUID
	OrganizationID   uuid.UUID
}

// Recalcula subtotal_cents desde las líneas reales — nunca se confía en un total que mandó el
// cliente — y BORRA cualquier promoción aplicada: un cambio en el carrito invalida un descuento
// calculado contra el subtotal anterior (ver internal/promotions). La llaman las mutaciones del
// carrito (agregar/cambiar/quitar una línea), nunca place(). delivery_fee_cents viene de las
// tarifas vigentes de la organización (internal/pricing): el carrito ya muestra el domicilio.
func (q *Queries) RecalcCartAmounts(ctx context.Context, arg RecalcCartAmountsParams) (Order, error) {
	row := q.db.QueryRow(ctx, recalcCartAmounts,
		arg.SubtotalCents,
		arg.DeliveryFeeCents,
		arg.TotalCents,
		arg.ID,
		arg.OrganizationID,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CustomerID,
		&i.Status,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.DeliveryFeeCents,
		&i.TotalCents,
		&i.PlacedAt,
		&i.StatusChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PromotionID,
		&i.SubtotalLocalCents,
		&i.PlatformFeeCents,
		&i.CourierFeeCents,
		&i.PricingSnapshot,
	)
	return i, err
}

const removePromotionFromOrder = `-- name: RemovePromotionFromOrder :one
UPDATE orders
SET promotion_id = NULL, discount_cents = 0, total_cents = subtotal_cents + delivery_fee_cents, updated_at = now()
WHERE id = $1 AND organization_id = $2 AND status = 'draft'
RETURNING id, organization_id, customer_id, status, subtotal_cents, discount_cents, delivery_fee_cents, total_cents, placed_at, status_changed_at, created_at, updated_at, promotion_id, subtotal_local_cents, platform_fee_cents, courier_fee_cents, pricing_snapshot
`

type RemovePromotionFromOrderParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

// Sin parámetro para total_cents: es pura aritmética de columnas (sin descuento, es
// subtotal + envío), no hace falta calcularla en Go.
func (q *Queries) RemovePromotionFromOrder(ctx context.Context, arg RemovePromotionFromOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, removePromotionFromOrder, arg.ID, arg.OrganizationID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CustomerID,
		&i.Status,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.DeliveryFeeCents,
		&i.TotalCents,
		&i.PlacedAt,
		&i.StatusChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PromotionID,
		&i.SubtotalLocalCents,
		&i.PlatformFeeCents,
		&i.CourierFeeCents,
		&i.PricingSnapshot,
	)
	return i, err
}

const setOrderAmounts = `-- name: SetOrderAmounts :one
UPDATE orders
SET subtotal_cents = $1, subtotal_local_cents = $2,
    platform_fee_cents = $3, delivery_fee_cents = $4,
    courier_fee_cents = $5, pricing_snapshot = $6,
    total_cents = $7, updated_at = now()
WHERE id = $8 AND organization_id = $9
RETURNING id, organization_id, customer_id, status, subtotal_cents, discount_cents, delivery_fee_cents, total_cents, placed_at, status_changed_at, created_at, updated_at, promotion_id, subtotal_local_cents, platform_fee_cents, courier_fee_cents, pricing_snapshot
`

type SetOrderAmountsParams struct {
	SubtotalCents      int32
	SubtotalLocalCents int32
	PlatformFeeCents   int32
	DeliveryFeeCents   int32
	CourierFeeCents    int32
	PricingSnapshot    []byte
	TotalCents         int32
	ID                 uuid.UUID
	OrganizationID     uuid.UUID
}

// Recalcula subtotal_cents y total_cents SIN tocar discount_cents/promotion_id (a diferencia de
// RecalcCartAmounts) — la llama place(): las líneas no debieron cambiar desde que se aplicó una
// promoción (eso ya la habría borrado), así que esto es sobre todo una confirmación. total_cents
// ya viene calculado desde Go (subtotal - descuento + envío, nunca negativo) — la aritmética de
// negocio vive ahí, no en SQL.
// Además congela lo que el pago necesita (docs/pagos.md §8): subtotal local (lo del restaurante),
// comisión de la plataforma, domicilio y la parte de él que se queda la plataforma, y las tarifas
// con que se calculó todo (pricing_snapshot).
func (q *Queries) SetOrderAmounts(ctx context.Context, arg SetOrderAmountsParams) (Order, error) {
	row := q.db.QueryRow(ctx, setOrderAmounts,
		arg.SubtotalCents,
		arg.SubtotalLocalCents,
		arg.PlatformFeeCents,
		arg.DeliveryFeeCents,
		arg.CourierFeeCents,
		arg.PricingSnapshot,
		arg.TotalCents,
		arg.ID,
		arg.OrganizationID,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CustomerID,
		&i.Status,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.DeliveryFeeCents,
		&i.TotalCents,
		&i.PlacedAt,
		&i.StatusChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PromotionID,
		&i.SubtotalLocalCents,
		&i.PlatformFeeCents,
		&i.CourierFeeCents,
		&i.PricingSnapshot,
	)
	return i, err
}

const sumOrderItems = `-- name: SumOrderItems :one
SELECT COALESCE(sum(line_total_cents), 0)::bigint FROM order_items WHERE order_id = $1
`

// Recalcula subtotal_cents desde las líneas reales — nunca se confía en un total que el cliente
// mandó por su cuenta.
func (q *Queries) SumOrderItems(ctx context.Context, orderID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumOrderItems, orderID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sumOrderItemsLocal = `-- name: SumOrderItemsLocal :one
SELECT COALESCE(sum(unit_local_total_cents::bigint * quantity), 0)::bigint FROM order_items WHERE order_id = $1
`

// La parte del restaurante en las líneas del pedido (precio local × cantidad).
func (q *Queries) SumOrderItemsLocal(ctx context.Context, orderID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumOrderItemsLocal, orderID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const transitionOrder = `-- name: TransitionOrder :one
UPDATE orders
SET status = $1,
    status_changed_at = now(),
    placed_at = CASE WHEN $2::boolean THEN now() ELSE placed_at END,
    updated_at = now()
WHERE id = $3 AND organization_id = $4 AND status = ANY($5::text[])
RETURNING id, organization_id, customer_id, status, subtotal_cents, discount_cents, delivery_fee_cents, total_cents, placed_at, status_changed_at, created_at, updated_at, promotion_id, subtotal_local_cents, platform_fee_cents, courier_fee_cents, pricing_snapshot
`

type TransitionOrderParams struct {
	Status         string
	SetPlacedAt    bool
	ID             uuid.UUID
	OrganizationID uuid.UUID
	FromStatuses   []string
}

// Una transición de estado. placed_at solo se toca al confirmar el carrito (@set_placed_at); los
// montos van aparte, por SetOrderAmounts — el resto de transiciones (aceptar, despachar...) no
// cambian lo que el cliente va a pagar.
func (q *Queries) TransitionOrder(ctx context.Context, arg TransitionOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, transitionOrder,
		arg.Status,
		arg.SetPlacedAt,
		arg.ID,
		arg.OrganizationID,
		arg.FromStatuses,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CustomerID,
		&i.Status,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.DeliveryFeeCents,
		&i.TotalCents,
		&i.PlacedAt,
		&i.StatusChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PromotionID,
		&i.SubtotalLocalCents,
		&i.PlatformFeeCents,
		&i.CourierFeeCents,
		&i.PricingSnapshot,
	)
	return i, err
}

const updateOrderItemQuantity = `-- name: UpdateOrderItemQuantity :one
UPDATE order_items
SET quantity = $1, line_total_cents = unit_total_cents * $1::int, updated_at = now()
WHERE id = $2 AND order_id = $3 AND organization_id = $4
RETURNING id, order_id, organization_id, product_variant_id, name_snapshot, unit_price_cents_snapshot, modifiers_snapshot, unit_total_cents, quantity, line_total_cents, created_at, updated_at, unit_local_total_cents, platform_fee_bps
`

type UpdateOrderItemQuantityParams struct {
	Quantity       int32
	ID             uuid.UUID
	OrderID        uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) UpdateOrderItemQuantity(ctx context.Context, arg UpdateOrderItemQuantityParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, updateOrderItemQuantity,
		arg.Quantity,
		arg.ID,
		arg.OrderID,
		arg.OrganizationID,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.OrganizationID,
		&i.ProductVariantID,
		&i.NameSnapshot,
		&i.UnitPriceCentsSnapshot,
		&i.ModifiersSnapshot,
		&i.UnitTotalCents,
		&i.Quantity,
		&i.LineTotalCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UnitLocalTotalCents,
		&i.PlatformFeeBps,
	)
	return i, err
}
