// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countMembers = `-- name: CountMembers :one
SELECT count(*) FROM user_organizations WHERE organization_id = $1
`

func (q *Queries) CountMembers(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMembers, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMembersWithRole = `-- name: CountMembersWithRole :one
SELECT count(*) FROM user_organizations WHERE role_id = $1
`

// Cuántos miembros tiene un rol (para no borrar uno en uso con un error de FK).
func (q *Queries) CountMembersWithRole(ctx context.Context, roleID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMembersWithRole, roleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrgManagers = `-- name: CountOrgManagers :one
SELECT count(*)
FROM user_organizations uo
JOIN role_permissions rp ON rp.role_id = uo.role_id AND rp.permission_code = 'org.members.manage'
WHERE uo.organization_id = $1
`

// Miembros que pueden administrar miembros: una organización nunca debe quedarse sin
// ninguno.
func (q *Queries) CountOrgManagers(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrgManagers, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublicOrganizations = `-- name: CountPublicOrganizations :one
SELECT count(*)
FROM organizations o
WHERE o.status = 'active'
  AND ($1::text IS NULL
        OR o.name ILIKE '%' || $1::text || '%'
        OR o.slug ILIKE '%' || $1::text || '%')
`

func (q *Queries) CountPublicOrganizations(ctx context.Context, search *string) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicOrganizations, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchOrganizations = `-- name: CountSearchOrganizations :one
SELECT count(*) FROM organizations o
WHERE ($1::text IS NULL
        OR o.name ILIKE '%' || $1::text || '%'
        OR o.slug ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL OR o.status = $2::text)
  AND ($3::text IS NULL OR o.plan_tier = $3::text)
`

type CountSearchOrganizationsParams struct {
	Search   *string
	Status   *string
	PlanTier *string
}

func (q *Queries) CountSearchOrganizations(ctx context.Context, arg CountSearchOrganizationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchOrganizations, arg.Search, arg.Status, arg.PlanTier)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMembership = `-- name: DeleteMembership :execrows
DELETE FROM user_organizations WHERE user_id = $1 AND organization_id = $2
`

type DeleteMembershipParams struct {
	UserID         uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMembership, arg.UserID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMembership = `-- name: GetMembership :one
SELECT uo.user_id, uo.organization_id, r.id AS role_id, r.code AS role_code, r.name AS role_name
FROM user_organizations uo
JOIN roles r ON r.id = uo.role_id
WHERE uo.user_id = $1 AND uo.organization_id = $2
`

type GetMembershipParams struct {
	UserID         uuid.UUID
	OrganizationID uuid.UUID
}

type GetMembershipRow struct {
	UserID         uuid.UUID
	OrganizationID uuid.UUID
	RoleID         uuid.UUID
	RoleCode       string
	RoleName       string
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (GetMembershipRow, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.OrganizationID)
	var i GetMembershipRow
	err := row.Scan(
		&i.UserID,
		&i.OrganizationID,
		&i.RoleID,
		&i.RoleCode,
		&i.RoleName,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, description, created_at, updated_at, slug, plan_tier, status, status_reason, status_changed_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.PlanTier,
		&i.Status,
		&i.StatusReason,
		&i.StatusChangedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, description, created_at, updated_at, slug, plan_tier, status, status_reason, status_changed_at FROM organizations WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.PlanTier,
		&i.Status,
		&i.StatusReason,
		&i.StatusChangedAt,
	)
	return i, err
}

const getOrganizationForUpdate = `-- name: GetOrganizationForUpdate :one
SELECT id, name, description, created_at, updated_at, slug, plan_tier, status, status_reason, status_changed_at FROM organizations WHERE id = $1 FOR UPDATE
`

// Bloquea la fila: los cambios de estado y de plan leen y escriben en una transacción.
func (q *Queries) GetOrganizationForUpdate(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationForUpdate, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.PlanTier,
		&i.Status,
		&i.StatusReason,
		&i.StatusChangedAt,
	)
	return i, err
}

const insertMembership = `-- name: InsertMembership :exec
INSERT INTO user_organizations (user_id, organization_id, role_id, created_at, updated_at)
VALUES ($1, $2, $3, timezone('utc', now()), timezone('utc', now()))
`

type InsertMembershipParams struct {
	UserID         uuid.UUID
	OrganizationID uuid.UUID
	RoleID         uuid.UUID
}

func (q *Queries) InsertMembership(ctx context.Context, arg InsertMembershipParams) error {
	_, err := q.db.Exec(ctx, insertMembership, arg.UserID, arg.OrganizationID, arg.RoleID)
	return err
}

const insertOrganization = `-- name: InsertOrganization :one
INSERT INTO organizations (id, name, slug, description, status, plan_tier, status_changed_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, 'active', $5, now(),
        timezone('utc', now()), timezone('utc', now()))
RETURNING id, name, description, created_at, updated_at, slug, plan_tier, status, status_reason, status_changed_at
`

type InsertOrganizationParams struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	Description *string
	PlanTier    string
}

func (q *Queries) InsertOrganization(ctx context.Context, arg InsertOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, insertOrganization,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.PlanTier,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.PlanTier,
		&i.Status,
		&i.StatusReason,
		&i.StatusChangedAt,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT uo.user_id, uo.organization_id, r.id AS role_id, r.code AS role_code, r.name AS role_name
FROM user_organizations uo
JOIN roles r ON r.id = uo.role_id
WHERE uo.organization_id = $1
ORDER BY uo.created_at, uo.user_id
`

type ListMembersRow struct {
	UserID         uuid.UUID
	OrganizationID uuid.UUID
	RoleID         uuid.UUID
	RoleCode       string
	RoleName       string
}

func (q *Queries) ListMembers(ctx context.Context, organizationID uuid.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.OrganizationID,
			&i.RoleID,
			&i.RoleCode,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, description, created_at, updated_at, slug, plan_tier, status, status_reason, status_changed_at FROM organizations WHERE status <> 'archived' ORDER BY name
`

// Las archivadas no salen en los listados corrientes; se piden con el filtro de estado.
func (q *Queries) ListOrganizations(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Slug,
			&i.PlanTier,
			&i.Status,
			&i.StatusReason,
			&i.StatusChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsByUser = `-- name: ListOrganizationsByUser :many
SELECT o.id, o.name, o.description, o.created_at, o.updated_at, o.slug, o.plan_tier, o.status, o.status_reason, o.status_changed_at
FROM organizations o
JOIN user_organizations uo ON uo.organization_id = o.id
WHERE uo.user_id = $1 AND o.status <> 'archived'
ORDER BY o.name
`

func (q *Queries) ListOrganizationsByUser(ctx context.Context, userID uuid.UUID) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Slug,
			&i.PlanTier,
			&i.Status,
			&i.StatusReason,
			&i.StatusChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicOrganizations = `-- name: ListPublicOrganizations :many
SELECT o.name, o.slug, o.description, s.logo_url, s.city
FROM organizations o
LEFT JOIN organization_settings s ON s.organization_id = o.id
WHERE o.status = 'active'
  AND ($1::text IS NULL
        OR o.name ILIKE '%' || $1::text || '%'
        OR o.slug ILIKE '%' || $1::text || '%')
ORDER BY o.name, o.id
LIMIT $3 OFFSET $2
`

type ListPublicOrganizationsParams struct {
	Search     *string
	PageOffset int32
	PageSize   int32
}

type ListPublicOrganizationsRow struct {
	Name        string
	Slug        string
	Description *string
	LogoUrl     *string
	City        *string
}

// Directorio público (app de cliente): solo activas, solo la cara del negocio.
// Sin business_hours/open_now aquí a propósito — eso es coste por fila (parsear
// jsonb y calcular contra la hora actual) que solo vale la pena en el detalle
// de una organización (ver Public/GetOrganizationBySlug), no en un listado.
// LEFT JOIN a propósito, igual que el fallback a DefaultSettings() en
// Settings(): una organización sin fila de ajustes (no debería pasar, pero
// que no desaparezca en silencio del directorio si pasa) sale con
// logo_url/city en null, no fuera de la lista.
func (q *Queries) ListPublicOrganizations(ctx context.Context, arg ListPublicOrganizationsParams) ([]ListPublicOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, listPublicOrganizations, arg.Search, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicOrganizationsRow{}
	for rows.Next() {
		var i ListPublicOrganizationsRow
		if err := rows.Scan(
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.LogoUrl,
			&i.City,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrganizationMembers = `-- name: LockOrganizationMembers :exec
SELECT pg_advisory_xact_lock(hashtextextended('org-members:' || $1::text, 0))
`

// Serializa los cambios de miembros de UNA organización (la clave es su id): dos
// peticiones simultáneas que cada una "deja a uno" dejarían a cero.
func (q *Queries) LockOrganizationMembers(ctx context.Context, organizationID string) error {
	_, err := q.db.Exec(ctx, lockOrganizationMembers, organizationID)
	return err
}

const organizationNameExists = `-- name: OrganizationNameExists :one
SELECT EXISTS (
    SELECT 1 FROM organizations
    WHERE lower(name) = lower($1)
      AND ($2::uuid IS NULL OR id <> $2::uuid))
`

type OrganizationNameExistsParams struct {
	Name     string
	ExceptID uuid.NullUUID
}

// Sin distinguir mayúsculas. except_id permite renombrar sin chocar con uno mismo.
func (q *Queries) OrganizationNameExists(ctx context.Context, arg OrganizationNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, organizationNameExists, arg.Name, arg.ExceptID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const organizationSlugExists = `-- name: OrganizationSlugExists :one
SELECT EXISTS (SELECT 1 FROM organizations WHERE slug = $1)
`

func (q *Queries) OrganizationSlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, organizationSlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const searchOrganizations = `-- name: SearchOrganizations :many
SELECT id, name, description, created_at, updated_at, slug, plan_tier, status, status_reason, status_changed_at FROM organizations o
WHERE ($1::text IS NULL
        OR o.name ILIKE '%' || $1::text || '%'
        OR o.slug ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL OR o.status = $2::text)
  AND ($3::text IS NULL OR o.plan_tier = $3::text)
ORDER BY o.name, o.id
LIMIT $5 OFFSET $4
`

type SearchOrganizationsParams struct {
	Search     *string
	Status     *string
	PlanTier   *string
	PageOffset int32
	PageSize   int32
}

// Listado de la plataforma. `search` ya viene escapado para LIKE.
func (q *Queries) SearchOrganizations(ctx context.Context, arg SearchOrganizationsParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, searchOrganizations,
		arg.Search,
		arg.Status,
		arg.PlanTier,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Slug,
			&i.PlanTier,
			&i.Status,
			&i.StatusReason,
			&i.StatusChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrganizationPlan = `-- name: SetOrganizationPlan :one
UPDATE organizations
SET plan_tier = $1, updated_at = timezone('utc', now())
WHERE id = $2
RETURNING id, name, description, created_at, updated_at, slug, plan_tier, status, status_reason, status_changed_at
`

type SetOrganizationPlanParams struct {
	PlanTier string
	ID       uuid.UUID
}

func (q *Queries) SetOrganizationPlan(ctx context.Context, arg SetOrganizationPlanParams) (Organization, error) {
	row := q.db.QueryRow(ctx, setOrganizationPlan, arg.PlanTier, arg.ID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.PlanTier,
		&i.Status,
		&i.StatusReason,
		&i.StatusChangedAt,
	)
	return i, err
}

const setOrganizationStatus = `-- name: SetOrganizationStatus :one
UPDATE organizations
SET status = $1, status_reason = $2, status_changed_at = now(),
    updated_at = timezone('utc', now())
WHERE id = $3
RETURNING id, name, description, created_at, updated_at, slug, plan_tier, status, status_reason, status_changed_at
`

type SetOrganizationStatusParams struct {
	Status string
	Reason *string
	ID     uuid.UUID
}

func (q *Queries) SetOrganizationStatus(ctx context.Context, arg SetOrganizationStatusParams) (Organization, error) {
	row := q.db.QueryRow(ctx, setOrganizationStatus, arg.Status, arg.Reason, arg.ID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.PlanTier,
		&i.Status,
		&i.StatusReason,
		&i.StatusChangedAt,
	)
	return i, err
}

const updateMembershipRole = `-- name: UpdateMembershipRole :execrows
UPDATE user_organizations
SET role_id = $1, updated_at = timezone('utc', now())
WHERE user_id = $2 AND organization_id = $3
`

type UpdateMembershipRoleParams struct {
	RoleID         uuid.UUID
	UserID         uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMembershipRole, arg.RoleID, arg.UserID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOrganizationProfile = `-- name: UpdateOrganizationProfile :one
UPDATE organizations
SET name = COALESCE($1, name),
    description = CASE WHEN $2::boolean THEN $3 ELSE description END,
    updated_at = timezone('utc', now())
WHERE id = $4
RETURNING id, name, description, created_at, updated_at, slug, plan_tier, status, status_reason, status_changed_at
`

type UpdateOrganizationProfileParams struct {
	Name           *string
	SetDescription bool
	Description    *string
	ID             uuid.UUID
}

// set_description distingue "no tocar" de "dejar en blanco".
func (q *Queries) UpdateOrganizationProfile(ctx context.Context, arg UpdateOrganizationProfileParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganizationProfile,
		arg.Name,
		arg.SetDescription,
		arg.Description,
		arg.ID,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.PlanTier,
		&i.Status,
		&i.StatusReason,
		&i.StatusChangedAt,
	)
	return i, err
}
