// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getPayment = `-- name: GetPayment :one
SELECT id, order_id, organization_id, status, amount_cents, currency, gateway, checkout_url, failure_reason, created_at, updated_at FROM payments WHERE id = $1 AND organization_id = $2
`

type GetPaymentParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) GetPayment(ctx context.Context, arg GetPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, arg.ID, arg.OrganizationID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.OrganizationID,
		&i.Status,
		&i.AmountCents,
		&i.Currency,
		&i.Gateway,
		&i.CheckoutUrl,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, order_id, organization_id, status, amount_cents, currency, gateway, checkout_url, failure_reason, created_at, updated_at FROM payments WHERE id = $1
`

// Sin organization_id: la usa el webhook de la pasarela, que solo conoce el id que le mandamos
// como referencia (p_id_invoice en ePayco) — igual motivo que orders.GetOrderByID.
func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.OrganizationID,
		&i.Status,
		&i.AmountCents,
		&i.Currency,
		&i.Gateway,
		&i.CheckoutUrl,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPayment = `-- name: InsertPayment :one
INSERT INTO payments (order_id, organization_id, amount_cents, currency, gateway)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, organization_id, status, amount_cents, currency, gateway, checkout_url, failure_reason, created_at, updated_at
`

type InsertPaymentParams struct {
	OrderID        uuid.UUID
	OrganizationID uuid.UUID
	AmountCents    int32
	Currency       string
	Gateway        string
}

func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, insertPayment,
		arg.OrderID,
		arg.OrganizationID,
		arg.AmountCents,
		arg.Currency,
		arg.Gateway,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.OrganizationID,
		&i.Status,
		&i.AmountCents,
		&i.Currency,
		&i.Gateway,
		&i.CheckoutUrl,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPaymentEvent = `-- name: InsertPaymentEvent :execrows
INSERT INTO payment_events (source, event_key, payload)
VALUES ($1, $2, $3)
ON CONFLICT (source, event_key) DO NOTHING
`

type InsertPaymentEventParams struct {
	Source   string
	EventKey string
	Payload  []byte
}

// Idempotencia: 0 filas afectadas significa que este evento ya se había registrado antes (mismo
// source + event_key) — el servicio lo trata como "ya se aplicó", no como un error.
func (q *Queries) InsertPaymentEvent(ctx context.Context, arg InsertPaymentEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPaymentEvent, arg.Source, arg.EventKey, arg.Payload)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPaymentsByOrder = `-- name: ListPaymentsByOrder :many
SELECT id, order_id, organization_id, status, amount_cents, currency, gateway, checkout_url, failure_reason, created_at, updated_at FROM payments WHERE order_id = $1 AND organization_id = $2 ORDER BY created_at DESC, id DESC
`

type ListPaymentsByOrderParams struct {
	OrderID        uuid.UUID
	OrganizationID uuid.UUID
}

// Aislamiento en la base, no solo en el código: aunque el servicio ya comprobó que el pedido es
// de esta organización, la consulta lo vuelve a exigir.
func (q *Queries) ListPaymentsByOrder(ctx context.Context, arg ListPaymentsByOrderParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByOrder, arg.OrderID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.OrganizationID,
			&i.Status,
			&i.AmountCents,
			&i.Currency,
			&i.Gateway,
			&i.CheckoutUrl,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPaymentCheckoutURL = `-- name: SetPaymentCheckoutURL :one
UPDATE payments SET checkout_url = $1, updated_at = now()
WHERE id = $2
RETURNING id, order_id, organization_id, status, amount_cents, currency, gateway, checkout_url, failure_reason, created_at, updated_at
`

type SetPaymentCheckoutURLParams struct {
	CheckoutUrl *string
	ID          uuid.UUID
}

func (q *Queries) SetPaymentCheckoutURL(ctx context.Context, arg SetPaymentCheckoutURLParams) (Payment, error) {
	row := q.db.QueryRow(ctx, setPaymentCheckoutURL, arg.CheckoutUrl, arg.ID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.OrganizationID,
		&i.Status,
		&i.AmountCents,
		&i.Currency,
		&i.Gateway,
		&i.CheckoutUrl,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const settlePayment = `-- name: SettlePayment :one
UPDATE payments
SET status = $1, failure_reason = $2, updated_at = now()
WHERE id = $3 AND status = 'pending'
RETURNING id, order_id, organization_id, status, amount_cents, currency, gateway, checkout_url, failure_reason, created_at, updated_at
`

type SettlePaymentParams struct {
	Status        string
	FailureReason *string
	ID            uuid.UUID
}

// Solo avanza desde 'pending': un evento repetido de la pasarela (reintento de webhook) no debe
// poder pisar un estado final ya aplicado. Si no coincide ninguna fila, el servicio lo trata como
// "ya se había procesado" — no como un error.
func (q *Queries) SettlePayment(ctx context.Context, arg SettlePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, settlePayment, arg.Status, arg.FailureReason, arg.ID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.OrganizationID,
		&i.Status,
		&i.AmountCents,
		&i.Currency,
		&i.Gateway,
		&i.CheckoutUrl,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
