// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const deleteFeatureOverride = `-- name: DeleteFeatureOverride :execrows
DELETE FROM organization_feature_overrides
WHERE organization_id = $1 AND feature = $2
`

type DeleteFeatureOverrideParams struct {
	OrganizationID uuid.UUID
	Feature        string
}

func (q *Queries) DeleteFeatureOverride(ctx context.Context, arg DeleteFeatureOverrideParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFeatureOverride, arg.OrganizationID, arg.Feature)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endCurrentSubscription = `-- name: EndCurrentSubscription :execrows
UPDATE organization_subscriptions SET ended_at = now()
WHERE organization_id = $1 AND ended_at IS NULL
`

func (q *Queries) EndCurrentSubscription(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, endCurrentSubscription, organizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCurrentSubscription = `-- name: GetCurrentSubscription :one
SELECT id, organization_id, plan_tier, started_at, ended_at, changed_by, reason FROM organization_subscriptions
WHERE organization_id = $1 AND ended_at IS NULL
`

func (q *Queries) GetCurrentSubscription(ctx context.Context, organizationID uuid.UUID) (OrganizationSubscription, error) {
	row := q.db.QueryRow(ctx, getCurrentSubscription, organizationID)
	var i OrganizationSubscription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanTier,
		&i.StartedAt,
		&i.EndedAt,
		&i.ChangedBy,
		&i.Reason,
	)
	return i, err
}

const insertSubscription = `-- name: InsertSubscription :one
INSERT INTO organization_subscriptions (organization_id, plan_tier, changed_by, reason)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, plan_tier, started_at, ended_at, changed_by, reason
`

type InsertSubscriptionParams struct {
	OrganizationID uuid.UUID
	PlanTier       string
	ChangedBy      uuid.NullUUID
	Reason         *string
}

func (q *Queries) InsertSubscription(ctx context.Context, arg InsertSubscriptionParams) (OrganizationSubscription, error) {
	row := q.db.QueryRow(ctx, insertSubscription,
		arg.OrganizationID,
		arg.PlanTier,
		arg.ChangedBy,
		arg.Reason,
	)
	var i OrganizationSubscription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanTier,
		&i.StartedAt,
		&i.EndedAt,
		&i.ChangedBy,
		&i.Reason,
	)
	return i, err
}

const listFeatureOverrides = `-- name: ListFeatureOverrides :many
SELECT organization_id, feature, enabled, reason, created_by, created_at FROM organization_feature_overrides
WHERE organization_id = $1
ORDER BY feature
`

func (q *Queries) ListFeatureOverrides(ctx context.Context, organizationID uuid.UUID) ([]OrganizationFeatureOverride, error) {
	rows, err := q.db.Query(ctx, listFeatureOverrides, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationFeatureOverride{}
	for rows.Next() {
		var i OrganizationFeatureOverride
		if err := rows.Scan(
			&i.OrganizationID,
			&i.Feature,
			&i.Enabled,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, organization_id, plan_tier, started_at, ended_at, changed_by, reason FROM organization_subscriptions
WHERE organization_id = $1
ORDER BY started_at DESC, id
`

func (q *Queries) ListSubscriptions(ctx context.Context, organizationID uuid.UUID) ([]OrganizationSubscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptions, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationSubscription{}
	for rows.Next() {
		var i OrganizationSubscription
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PlanTier,
			&i.StartedAt,
			&i.EndedAt,
			&i.ChangedBy,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFeatureOverride = `-- name: UpsertFeatureOverride :one
INSERT INTO organization_feature_overrides (organization_id, feature, enabled, reason, created_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (organization_id, feature)
DO UPDATE SET enabled = EXCLUDED.enabled, reason = EXCLUDED.reason,
              created_by = EXCLUDED.created_by, created_at = now()
RETURNING organization_id, feature, enabled, reason, created_by, created_at
`

type UpsertFeatureOverrideParams struct {
	OrganizationID uuid.UUID
	Feature        string
	Enabled        bool
	Reason         *string
	CreatedBy      uuid.NullUUID
}

func (q *Queries) UpsertFeatureOverride(ctx context.Context, arg UpsertFeatureOverrideParams) (OrganizationFeatureOverride, error) {
	row := q.db.QueryRow(ctx, upsertFeatureOverride,
		arg.OrganizationID,
		arg.Feature,
		arg.Enabled,
		arg.Reason,
		arg.CreatedBy,
	)
	var i OrganizationFeatureOverride
	err := row.Scan(
		&i.OrganizationID,
		&i.Feature,
		&i.Enabled,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
