// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pricing.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getGatewayFeePlan = `-- name: GetGatewayFeePlan :one
SELECT code, gateway, name, card_percent_bps, card_fixed_cents, international_extra_bps, wallet_percent_bps, wallet_fixed_cents, pse_percent_bps, pse_fixed_cents, pse_small_threshold_cents, pse_small_fixed_cents, vat_bps, notes, updated_by, updated_at FROM gateway_fee_plans WHERE code = $1
`

func (q *Queries) GetGatewayFeePlan(ctx context.Context, code string) (GatewayFeePlan, error) {
	row := q.db.QueryRow(ctx, getGatewayFeePlan, code)
	var i GatewayFeePlan
	err := row.Scan(
		&i.Code,
		&i.Gateway,
		&i.Name,
		&i.CardPercentBps,
		&i.CardFixedCents,
		&i.InternationalExtraBps,
		&i.WalletPercentBps,
		&i.WalletFixedCents,
		&i.PsePercentBps,
		&i.PseFixedCents,
		&i.PseSmallThresholdCents,
		&i.PseSmallFixedCents,
		&i.VatBps,
		&i.Notes,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationPricing = `-- name: GetOrganizationPricing :one
SELECT organization_id, platform_fee_bps, promo_platform_fee_bps, courier_fee_bps, delivery_fee_cents, gateway_plan_code, epayco_merchant_id, updated_by, updated_at FROM organization_pricing WHERE organization_id = $1
`

func (q *Queries) GetOrganizationPricing(ctx context.Context, organizationID uuid.UUID) (OrganizationPricing, error) {
	row := q.db.QueryRow(ctx, getOrganizationPricing, organizationID)
	var i OrganizationPricing
	err := row.Scan(
		&i.OrganizationID,
		&i.PlatformFeeBps,
		&i.PromoPlatformFeeBps,
		&i.CourierFeeBps,
		&i.DeliveryFeeCents,
		&i.GatewayPlanCode,
		&i.EpaycoMerchantID,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getPricingSettings = `-- name: GetPricingSettings :one
SELECT id, platform_fee_bps, promo_platform_fee_bps, courier_fee_bps, delivery_fee_cents, gateway_plan_code, split_enabled, updated_by, updated_at FROM pricing_settings WHERE id
`

func (q *Queries) GetPricingSettings(ctx context.Context) (PricingSetting, error) {
	row := q.db.QueryRow(ctx, getPricingSettings)
	var i PricingSetting
	err := row.Scan(
		&i.ID,
		&i.PlatformFeeBps,
		&i.PromoPlatformFeeBps,
		&i.CourierFeeBps,
		&i.DeliveryFeeCents,
		&i.GatewayPlanCode,
		&i.SplitEnabled,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listGatewayFeePlans = `-- name: ListGatewayFeePlans :many
SELECT code, gateway, name, card_percent_bps, card_fixed_cents, international_extra_bps, wallet_percent_bps, wallet_fixed_cents, pse_percent_bps, pse_fixed_cents, pse_small_threshold_cents, pse_small_fixed_cents, vat_bps, notes, updated_by, updated_at FROM gateway_fee_plans ORDER BY code
`

func (q *Queries) ListGatewayFeePlans(ctx context.Context) ([]GatewayFeePlan, error) {
	rows, err := q.db.Query(ctx, listGatewayFeePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GatewayFeePlan{}
	for rows.Next() {
		var i GatewayFeePlan
		if err := rows.Scan(
			&i.Code,
			&i.Gateway,
			&i.Name,
			&i.CardPercentBps,
			&i.CardFixedCents,
			&i.InternationalExtraBps,
			&i.WalletPercentBps,
			&i.WalletFixedCents,
			&i.PsePercentBps,
			&i.PseFixedCents,
			&i.PseSmallThresholdCents,
			&i.PseSmallFixedCents,
			&i.VatBps,
			&i.Notes,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsPricing = `-- name: ListOrganizationsPricing :many
SELECT o.id, o.name, o.slug, o.status,
       op.platform_fee_bps, op.promo_platform_fee_bps, op.courier_fee_bps, op.delivery_fee_cents,
       op.gateway_plan_code, op.epayco_merchant_id, op.updated_at
FROM organizations o
LEFT JOIN organization_pricing op ON op.organization_id = o.id
WHERE o.status <> 'archived'
ORDER BY o.name
`

type ListOrganizationsPricingRow struct {
	ID                  uuid.UUID
	Name                string
	Slug                string
	Status              string
	PlatformFeeBps      *int32
	PromoPlatformFeeBps *int32
	CourierFeeBps       *int32
	DeliveryFeeCents    *int32
	GatewayPlanCode     *string
	EpaycoMerchantID    *string
	UpdatedAt           pgtype.Timestamptz
}

// La vista general del superadmin: todas las organizaciones (no archivadas) con lo que tengan
// sobrescrito, si algo.
func (q *Queries) ListOrganizationsPricing(ctx context.Context) ([]ListOrganizationsPricingRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationsPricing)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationsPricingRow{}
	for rows.Next() {
		var i ListOrganizationsPricingRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.PlatformFeeBps,
			&i.PromoPlatformFeeBps,
			&i.CourierFeeBps,
			&i.DeliveryFeeCents,
			&i.GatewayPlanCode,
			&i.EpaycoMerchantID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGatewayFeePlan = `-- name: UpdateGatewayFeePlan :one
UPDATE gateway_fee_plans
SET name = $1, card_percent_bps = $2, card_fixed_cents = $3,
    international_extra_bps = $4,
    wallet_percent_bps = $5, wallet_fixed_cents = $6,
    pse_percent_bps = $7, pse_fixed_cents = $8,
    pse_small_threshold_cents = $9, pse_small_fixed_cents = $10,
    vat_bps = $11, notes = $12, updated_by = $13, updated_at = now()
WHERE code = $14
RETURNING code, gateway, name, card_percent_bps, card_fixed_cents, international_extra_bps, wallet_percent_bps, wallet_fixed_cents, pse_percent_bps, pse_fixed_cents, pse_small_threshold_cents, pse_small_fixed_cents, vat_bps, notes, updated_by, updated_at
`

type UpdateGatewayFeePlanParams struct {
	Name                   string
	CardPercentBps         int32
	CardFixedCents         int32
	InternationalExtraBps  int32
	WalletPercentBps       int32
	WalletFixedCents       int32
	PsePercentBps          int32
	PseFixedCents          int32
	PseSmallThresholdCents int32
	PseSmallFixedCents     int32
	VatBps                 int32
	Notes                  *string
	UpdatedBy              uuid.NullUUID
	Code                   string
}

func (q *Queries) UpdateGatewayFeePlan(ctx context.Context, arg UpdateGatewayFeePlanParams) (GatewayFeePlan, error) {
	row := q.db.QueryRow(ctx, updateGatewayFeePlan,
		arg.Name,
		arg.CardPercentBps,
		arg.CardFixedCents,
		arg.InternationalExtraBps,
		arg.WalletPercentBps,
		arg.WalletFixedCents,
		arg.PsePercentBps,
		arg.PseFixedCents,
		arg.PseSmallThresholdCents,
		arg.PseSmallFixedCents,
		arg.VatBps,
		arg.Notes,
		arg.UpdatedBy,
		arg.Code,
	)
	var i GatewayFeePlan
	err := row.Scan(
		&i.Code,
		&i.Gateway,
		&i.Name,
		&i.CardPercentBps,
		&i.CardFixedCents,
		&i.InternationalExtraBps,
		&i.WalletPercentBps,
		&i.WalletFixedCents,
		&i.PsePercentBps,
		&i.PseFixedCents,
		&i.PseSmallThresholdCents,
		&i.PseSmallFixedCents,
		&i.VatBps,
		&i.Notes,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePricingSettings = `-- name: UpdatePricingSettings :one
UPDATE pricing_settings
SET platform_fee_bps = $1, promo_platform_fee_bps = $2,
    courier_fee_bps = $3, delivery_fee_cents = $4,
    gateway_plan_code = $5, split_enabled = $6,
    updated_by = $7, updated_at = now()
WHERE id
RETURNING id, platform_fee_bps, promo_platform_fee_bps, courier_fee_bps, delivery_fee_cents, gateway_plan_code, split_enabled, updated_by, updated_at
`

type UpdatePricingSettingsParams struct {
	PlatformFeeBps      int32
	PromoPlatformFeeBps int32
	CourierFeeBps       int32
	DeliveryFeeCents    int32
	GatewayPlanCode     string
	SplitEnabled        bool
	UpdatedBy           uuid.NullUUID
}

func (q *Queries) UpdatePricingSettings(ctx context.Context, arg UpdatePricingSettingsParams) (PricingSetting, error) {
	row := q.db.QueryRow(ctx, updatePricingSettings,
		arg.PlatformFeeBps,
		arg.PromoPlatformFeeBps,
		arg.CourierFeeBps,
		arg.DeliveryFeeCents,
		arg.GatewayPlanCode,
		arg.SplitEnabled,
		arg.UpdatedBy,
	)
	var i PricingSetting
	err := row.Scan(
		&i.ID,
		&i.PlatformFeeBps,
		&i.PromoPlatformFeeBps,
		&i.CourierFeeBps,
		&i.DeliveryFeeCents,
		&i.GatewayPlanCode,
		&i.SplitEnabled,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrganizationPricing = `-- name: UpsertOrganizationPricing :one
INSERT INTO organization_pricing (organization_id, platform_fee_bps, promo_platform_fee_bps, courier_fee_bps,
    delivery_fee_cents, gateway_plan_code, epayco_merchant_id, updated_by)
VALUES ($1, $2, $3, $4,
    $5, $6, $7, $8)
ON CONFLICT (organization_id) DO UPDATE
SET platform_fee_bps = EXCLUDED.platform_fee_bps, promo_platform_fee_bps = EXCLUDED.promo_platform_fee_bps,
    courier_fee_bps = EXCLUDED.courier_fee_bps, delivery_fee_cents = EXCLUDED.delivery_fee_cents,
    gateway_plan_code = EXCLUDED.gateway_plan_code, epayco_merchant_id = EXCLUDED.epayco_merchant_id,
    updated_by = EXCLUDED.updated_by, updated_at = now()
RETURNING organization_id, platform_fee_bps, promo_platform_fee_bps, courier_fee_bps, delivery_fee_cents, gateway_plan_code, epayco_merchant_id, updated_by, updated_at
`

type UpsertOrganizationPricingParams struct {
	OrganizationID      uuid.UUID
	PlatformFeeBps      *int32
	PromoPlatformFeeBps *int32
	CourierFeeBps       *int32
	DeliveryFeeCents    *int32
	GatewayPlanCode     *string
	EpaycoMerchantID    *string
	UpdatedBy           uuid.UUID
}

// Reemplaza la configuración propia de una organización. Cada campo NULL = hereda de la general.
func (q *Queries) UpsertOrganizationPricing(ctx context.Context, arg UpsertOrganizationPricingParams) (OrganizationPricing, error) {
	row := q.db.QueryRow(ctx, upsertOrganizationPricing,
		arg.OrganizationID,
		arg.PlatformFeeBps,
		arg.PromoPlatformFeeBps,
		arg.CourierFeeBps,
		arg.DeliveryFeeCents,
		arg.GatewayPlanCode,
		arg.EpaycoMerchantID,
		arg.UpdatedBy,
	)
	var i OrganizationPricing
	err := row.Scan(
		&i.OrganizationID,
		&i.PlatformFeeBps,
		&i.PromoPlatformFeeBps,
		&i.CourierFeeBps,
		&i.DeliveryFeeCents,
		&i.GatewayPlanCode,
		&i.EpaycoMerchantID,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
