// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: promotions.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCustomerPromotionRedemptions = `-- name: CountCustomerPromotionRedemptions :one
SELECT count(*) FROM promotion_redemptions pr
JOIN orders o ON o.id = pr.order_id
WHERE pr.promotion_id = $1 AND pr.customer_id = $2
  AND o.status <> 'draft' AND o.promotion_id = pr.promotion_id
`

type CountCustomerPromotionRedemptionsParams struct {
	PromotionID uuid.UUID
	CustomerID  uuid.UUID
}

func (q *Queries) CountCustomerPromotionRedemptions(ctx context.Context, arg CountCustomerPromotionRedemptionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomerPromotionRedemptions, arg.PromotionID, arg.CustomerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPromotionRedemptions = `-- name: CountPromotionRedemptions :one
SELECT count(*) FROM promotion_redemptions pr
JOIN orders o ON o.id = pr.order_id
WHERE pr.promotion_id = $1 AND o.status <> 'draft' AND o.promotion_id = pr.promotion_id
`

// Un canje solo cuenta si el pedido ya dejó de ser un borrador Y sigue siendo esta la promoción
// vigente en él (ver el comentario de la migración 00008): editar el carrito después de aplicar
// un código lo borra de orders.promotion_id, así que ese canje deja de contar sin que nadie tenga
// que limpiarlo a mano.
func (q *Queries) CountPromotionRedemptions(ctx context.Context, promotionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPromotionRedemptions, promotionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePromotionRedemptionByOrder = `-- name: DeletePromotionRedemptionByOrder :exec
DELETE FROM promotion_redemptions WHERE order_id = $1
`

// Reemplaza el canje del pedido (nunca lo acumula): aplicar OTRO código sobre el mismo carrito
// pisa el anterior. Se borra primero (no ON CONFLICT) porque el nuevo puede ser de OTRA
// promoción, y el UNIQUE es solo por order_id.
func (q *Queries) DeletePromotionRedemptionByOrder(ctx context.Context, orderID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePromotionRedemptionByOrder, orderID)
	return err
}

const getActivePromotionByCode = `-- name: GetActivePromotionByCode :one
SELECT id, organization_id, code, discount_type, value, min_order_cents, starts_at, ends_at, max_uses, per_customer_limit, is_active, created_at, updated_at FROM promotions WHERE organization_id = $1 AND upper(code) = upper($2::text) AND is_active
`

type GetActivePromotionByCodeParams struct {
	OrganizationID uuid.UUID
	Code           string
}

// Sin distinguir mayúsculas, y solo entre las activas — el mismo criterio que hace único el
// código (ver el índice parcial de la migración): si hay una desactivada con el mismo texto, no
// es ambigüedad, esa ya no cuenta.
func (q *Queries) GetActivePromotionByCode(ctx context.Context, arg GetActivePromotionByCodeParams) (Promotion, error) {
	row := q.db.QueryRow(ctx, getActivePromotionByCode, arg.OrganizationID, arg.Code)
	var i Promotion
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.DiscountType,
		&i.Value,
		&i.MinOrderCents,
		&i.StartsAt,
		&i.EndsAt,
		&i.MaxUses,
		&i.PerCustomerLimit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPromotion = `-- name: GetPromotion :one
SELECT id, organization_id, code, discount_type, value, min_order_cents, starts_at, ends_at, max_uses, per_customer_limit, is_active, created_at, updated_at FROM promotions WHERE id = $1 AND organization_id = $2
`

type GetPromotionParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) GetPromotion(ctx context.Context, arg GetPromotionParams) (Promotion, error) {
	row := q.db.QueryRow(ctx, getPromotion, arg.ID, arg.OrganizationID)
	var i Promotion
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.DiscountType,
		&i.Value,
		&i.MinOrderCents,
		&i.StartsAt,
		&i.EndsAt,
		&i.MaxUses,
		&i.PerCustomerLimit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPromotion = `-- name: InsertPromotion :one
INSERT INTO promotions (
    organization_id, code, discount_type, value, min_order_cents,
    starts_at, ends_at, max_uses, per_customer_limit
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
)
RETURNING id, organization_id, code, discount_type, value, min_order_cents, starts_at, ends_at, max_uses, per_customer_limit, is_active, created_at, updated_at
`

type InsertPromotionParams struct {
	OrganizationID   uuid.UUID
	Code             string
	DiscountType     string
	Value            int32
	MinOrderCents    int32
	StartsAt         pgtype.Timestamptz
	EndsAt           pgtype.Timestamptz
	MaxUses          *int32
	PerCustomerLimit *int32
}

func (q *Queries) InsertPromotion(ctx context.Context, arg InsertPromotionParams) (Promotion, error) {
	row := q.db.QueryRow(ctx, insertPromotion,
		arg.OrganizationID,
		arg.Code,
		arg.DiscountType,
		arg.Value,
		arg.MinOrderCents,
		arg.StartsAt,
		arg.EndsAt,
		arg.MaxUses,
		arg.PerCustomerLimit,
	)
	var i Promotion
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.DiscountType,
		&i.Value,
		&i.MinOrderCents,
		&i.StartsAt,
		&i.EndsAt,
		&i.MaxUses,
		&i.PerCustomerLimit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPromotionRedemption = `-- name: InsertPromotionRedemption :one
INSERT INTO promotion_redemptions (promotion_id, organization_id, order_id, customer_id, discount_cents)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, promotion_id, organization_id, order_id, customer_id, discount_cents, applied_at
`

type InsertPromotionRedemptionParams struct {
	PromotionID    uuid.UUID
	OrganizationID uuid.UUID
	OrderID        uuid.UUID
	CustomerID     uuid.UUID
	DiscountCents  int32
}

func (q *Queries) InsertPromotionRedemption(ctx context.Context, arg InsertPromotionRedemptionParams) (PromotionRedemption, error) {
	row := q.db.QueryRow(ctx, insertPromotionRedemption,
		arg.PromotionID,
		arg.OrganizationID,
		arg.OrderID,
		arg.CustomerID,
		arg.DiscountCents,
	)
	var i PromotionRedemption
	err := row.Scan(
		&i.ID,
		&i.PromotionID,
		&i.OrganizationID,
		&i.OrderID,
		&i.CustomerID,
		&i.DiscountCents,
		&i.AppliedAt,
	)
	return i, err
}

const listPromotions = `-- name: ListPromotions :many
SELECT id, organization_id, code, discount_type, value, min_order_cents, starts_at, ends_at, max_uses, per_customer_limit, is_active, created_at, updated_at FROM promotions WHERE organization_id = $1 ORDER BY created_at DESC, id
`

func (q *Queries) ListPromotions(ctx context.Context, organizationID uuid.UUID) ([]Promotion, error) {
	rows, err := q.db.Query(ctx, listPromotions, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Promotion{}
	for rows.Next() {
		var i Promotion
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Code,
			&i.DiscountType,
			&i.Value,
			&i.MinOrderCents,
			&i.StartsAt,
			&i.EndsAt,
			&i.MaxUses,
			&i.PerCustomerLimit,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePromotion = `-- name: UpdatePromotion :one
UPDATE promotions
SET code               = COALESCE($1, code),
    discount_type      = COALESCE($2, discount_type),
    value              = COALESCE($3, value),
    min_order_cents    = COALESCE($4, min_order_cents),
    starts_at          = CASE WHEN $5::boolean THEN $6 ELSE starts_at END,
    ends_at            = CASE WHEN $7::boolean THEN $8 ELSE ends_at END,
    max_uses           = CASE WHEN $9::boolean THEN $10 ELSE max_uses END,
    per_customer_limit = CASE WHEN $11::boolean THEN $12 ELSE per_customer_limit END,
    is_active          = COALESCE($13, is_active),
    updated_at         = now()
WHERE id = $14 AND organization_id = $15
RETURNING id, organization_id, code, discount_type, value, min_order_cents, starts_at, ends_at, max_uses, per_customer_limit, is_active, created_at, updated_at
`

type UpdatePromotionParams struct {
	Code                *string
	DiscountType        *string
	Value               *int32
	MinOrderCents       *int32
	SetStartsAt         bool
	StartsAt            pgtype.Timestamptz
	SetEndsAt           bool
	EndsAt              pgtype.Timestamptz
	SetMaxUses          bool
	MaxUses             *int32
	SetPerCustomerLimit bool
	PerCustomerLimit    *int32
	IsActive            *bool
	ID                  uuid.UUID
	OrganizationID      uuid.UUID
}

// Cambio parcial: set_* distingue "no tocar" de "dejar en blanco" en starts_at/ends_at/max_uses/
// per_customer_limit (sí admiten null: "sin fecha de inicio", "sin límite de usos"...). code,
// discount_type, value y min_order_cents nunca se ponen en blanco, así que un ausente
// (COALESCE) basta.
func (q *Queries) UpdatePromotion(ctx context.Context, arg UpdatePromotionParams) (Promotion, error) {
	row := q.db.QueryRow(ctx, updatePromotion,
		arg.Code,
		arg.DiscountType,
		arg.Value,
		arg.MinOrderCents,
		arg.SetStartsAt,
		arg.StartsAt,
		arg.SetEndsAt,
		arg.EndsAt,
		arg.SetMaxUses,
		arg.MaxUses,
		arg.SetPerCustomerLimit,
		arg.PerCustomerLimit,
		arg.IsActive,
		arg.ID,
		arg.OrganizationID,
	)
	var i Promotion
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.DiscountType,
		&i.Value,
		&i.MinOrderCents,
		&i.StartsAt,
		&i.EndsAt,
		&i.MaxUses,
		&i.PerCustomerLimit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
