// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countActiveUsersWithPlatformRole = `-- name: CountActiveUsersWithPlatformRole :one
SELECT count(*) FROM user_platform_roles upr
JOIN roles r ON r.id = upr.role_id
JOIN users u ON u.id = upr.user_id
WHERE r.scope = 'platform' AND r.organization_id IS NULL AND r.code = $1 AND u.is_active
`

// Usuarios ACTIVOS con un rol de plataforma: para no quedarse sin superadmin.
func (q *Queries) CountActiveUsersWithPlatformRole(ctx context.Context, code string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUsersWithPlatformRole, code)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAudit = `-- name: CountAudit :one
SELECT count(*) FROM audit_log
WHERE ($1::uuid IS NULL OR organization_id = $1::uuid)
  AND ($2::uuid IS NULL OR target_user_id = $2::uuid)
  AND ($3::text IS NULL OR action = $3::text)
`

type CountAuditParams struct {
	OrganizationID uuid.NullUUID
	TargetUserID   uuid.NullUUID
	Action         *string
}

func (q *Queries) CountAudit(ctx context.Context, arg CountAuditParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAudit, arg.OrganizationID, arg.TargetUserID, arg.Action)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersWithPlatformRole = `-- name: CountUsersWithPlatformRole :one
SELECT count(*) FROM user_platform_roles upr
JOIN roles r ON r.id = upr.role_id
WHERE r.scope = 'platform' AND r.organization_id IS NULL AND r.code = $1
`

func (q *Queries) CountUsersWithPlatformRole(ctx context.Context, code string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersWithPlatformRole, code)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersWithPlatformRoleID = `-- name: CountUsersWithPlatformRoleID :one
SELECT count(*) FROM user_platform_roles WHERE role_id = $1
`

func (q *Queries) CountUsersWithPlatformRoleID(ctx context.Context, roleID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersWithPlatformRoleID, roleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRole = `-- name: DeleteRole :execrows
DELETE FROM roles WHERE id = $1 AND NOT is_system
`

func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRole, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) DeleteRolePermissions(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, roleID)
	return err
}

const deleteUserPlatformRole = `-- name: DeleteUserPlatformRole :execrows
DELETE FROM user_platform_roles WHERE user_id = $1 AND role_id = $2
`

type DeleteUserPlatformRoleParams struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}

func (q *Queries) DeleteUserPlatformRole(ctx context.Context, arg DeleteUserPlatformRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserPlatformRole, arg.UserID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrgRoleByCode = `-- name: GetOrgRoleByCode :one
SELECT id, code, name, description, scope, organization_id, is_system, org_assignable, created_at, updated_at FROM roles WHERE organization_id = $1 AND code = $2
`

type GetOrgRoleByCodeParams struct {
	OrganizationID uuid.NullUUID
	Code           string
}

// Rol personalizado de una organización por código.
func (q *Queries) GetOrgRoleByCode(ctx context.Context, arg GetOrgRoleByCodeParams) (Role, error) {
	row := q.db.QueryRow(ctx, getOrgRoleByCode, arg.OrganizationID, arg.Code)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.OrganizationID,
		&i.IsSystem,
		&i.OrgAssignable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRole = `-- name: GetRole :one

SELECT id, code, name, description, scope, organization_id, is_system, org_assignable, created_at, updated_at FROM roles WHERE id = $1
`

// ---------------------------------------------------------------------------
// Roles
// ---------------------------------------------------------------------------
func (q *Queries) GetRole(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.OrganizationID,
		&i.IsSystem,
		&i.OrgAssignable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSystemRoleByCode = `-- name: GetSystemRoleByCode :one
SELECT id, code, name, description, scope, organization_id, is_system, org_assignable, created_at, updated_at FROM roles WHERE organization_id IS NULL AND scope = $1 AND code = $2
`

type GetSystemRoleByCodeParams struct {
	Scope string
	Code  string
}

// Rol de sistema (sin organización) por código y alcance.
func (q *Queries) GetSystemRoleByCode(ctx context.Context, arg GetSystemRoleByCodeParams) (Role, error) {
	row := q.db.QueryRow(ctx, getSystemRoleByCode, arg.Scope, arg.Code)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.OrganizationID,
		&i.IsSystem,
		&i.OrgAssignable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAudit = `-- name: InsertAudit :exec

INSERT INTO audit_log (actor_id, action, target_user_id, organization_id, role_id, role_code, detail)
VALUES ($1, $2, $3, $4,
        $5, $6, $7)
`

type InsertAuditParams struct {
	ActorID        uuid.NullUUID
	Action         string
	TargetUserID   uuid.NullUUID
	OrganizationID uuid.NullUUID
	RoleID         uuid.NullUUID
	RoleCode       *string
	Detail         []byte
}

// ---------------------------------------------------------------------------
// Auditoría
// ---------------------------------------------------------------------------
func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.ActorID,
		arg.Action,
		arg.TargetUserID,
		arg.OrganizationID,
		arg.RoleID,
		arg.RoleCode,
		arg.Detail,
	)
	return err
}

const insertRole = `-- name: InsertRole :one
INSERT INTO roles (code, name, description, scope, organization_id, is_system, org_assignable)
VALUES ($1, $2, $3, $4, $5, FALSE, $6)
RETURNING id, code, name, description, scope, organization_id, is_system, org_assignable, created_at, updated_at
`

type InsertRoleParams struct {
	Code           string
	Name           string
	Description    *string
	Scope          string
	OrganizationID uuid.NullUUID
	OrgAssignable  bool
}

func (q *Queries) InsertRole(ctx context.Context, arg InsertRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, insertRole,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Scope,
		arg.OrganizationID,
		arg.OrgAssignable,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.OrganizationID,
		&i.IsSystem,
		&i.OrgAssignable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRolePermissions = `-- name: InsertRolePermissions :exec
INSERT INTO role_permissions (role_id, permission_code)
SELECT $1, unnest($2::text[])
`

type InsertRolePermissionsParams struct {
	RoleID          uuid.UUID
	PermissionCodes []string
}

func (q *Queries) InsertRolePermissions(ctx context.Context, arg InsertRolePermissionsParams) error {
	_, err := q.db.Exec(ctx, insertRolePermissions, arg.RoleID, arg.PermissionCodes)
	return err
}

const insertUserPlatformRole = `-- name: InsertUserPlatformRole :execrows
INSERT INTO user_platform_roles (user_id, role_id, granted_by)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, role_id) DO NOTHING
`

type InsertUserPlatformRoleParams struct {
	UserID    uuid.UUID
	RoleID    uuid.UUID
	GrantedBy uuid.NullUUID
}

// Idempotente: dar dos veces el mismo rol no es un error.
func (q *Queries) InsertUserPlatformRole(ctx context.Context, arg InsertUserPlatformRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertUserPlatformRole, arg.UserID, arg.RoleID, arg.GrantedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertUserPlatformRoleByCode = `-- name: InsertUserPlatformRoleByCode :execrows
INSERT INTO user_platform_roles (user_id, role_id, granted_by)
SELECT $1::uuid, r.id, $2::uuid
FROM roles r
WHERE r.scope = 'platform' AND r.organization_id IS NULL AND r.code = $3
ON CONFLICT (user_id, role_id) DO NOTHING
`

type InsertUserPlatformRoleByCodeParams struct {
	UserID    uuid.UUID
	GrantedBy uuid.NullUUID
	Code      string
}

// Lo mismo por código de rol de sistema (altas de cliente y de domiciliario).
func (q *Queries) InsertUserPlatformRoleByCode(ctx context.Context, arg InsertUserPlatformRoleByCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertUserPlatformRoleByCode, arg.UserID, arg.GrantedBy, arg.Code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAudit = `-- name: ListAudit :many
SELECT id, actor_id, action, target_user_id, organization_id, role_id, role_code, detail, created_at FROM audit_log
WHERE ($1::uuid IS NULL OR organization_id = $1::uuid)
  AND ($2::uuid IS NULL OR target_user_id = $2::uuid)
  AND ($3::text IS NULL OR action = $3::text)
ORDER BY created_at DESC, id
LIMIT $5 OFFSET $4
`

type ListAuditParams struct {
	OrganizationID uuid.NullUUID
	TargetUserID   uuid.NullUUID
	Action         *string
	PageOffset     int32
	PageSize       int32
}

func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAudit,
		arg.OrganizationID,
		arg.TargetUserID,
		arg.Action,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.TargetUserID,
			&i.OrganizationID,
			&i.RoleID,
			&i.RoleCode,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many

SELECT code, scope, description, delegable FROM permissions ORDER BY scope, code
`

// ---------------------------------------------------------------------------
// Permisos de un rol
// ---------------------------------------------------------------------------
func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.Code,
			&i.Scope,
			&i.Description,
			&i.Delegable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformRolesForUsers = `-- name: ListPlatformRolesForUsers :many
SELECT upr.user_id, r.id AS role_id, r.code AS role_code, r.name AS role_name
FROM user_platform_roles upr
JOIN roles r ON r.id = upr.role_id
WHERE upr.user_id = ANY($1::uuid[])
ORDER BY upr.user_id, r.code
`

type ListPlatformRolesForUsersRow struct {
	UserID   uuid.UUID
	RoleID   uuid.UUID
	RoleCode string
	RoleName string
}

func (q *Queries) ListPlatformRolesForUsers(ctx context.Context, userIds []uuid.UUID) ([]ListPlatformRolesForUsersRow, error) {
	rows, err := q.db.Query(ctx, listPlatformRolesForUsers, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformRolesForUsersRow{}
	for rows.Next() {
		var i ListPlatformRolesForUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.RoleID,
			&i.RoleCode,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissions = `-- name: ListRolePermissions :many
SELECT role_id, permission_code FROM role_permissions
WHERE role_id = ANY($1::uuid[])
ORDER BY role_id, permission_code
`

func (q *Queries) ListRolePermissions(ctx context.Context, roleIds []uuid.UUID) ([]RolePermission, error) {
	rows, err := q.db.Query(ctx, listRolePermissions, roleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RolePermission{}
	for rows.Next() {
		var i RolePermission
		if err := rows.Scan(&i.RoleID, &i.PermissionCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, code, name, description, scope, organization_id, is_system, org_assignable, created_at, updated_at FROM roles
WHERE ($1::text IS NULL OR scope = $1::text)
  AND ($2::uuid IS NULL OR organization_id = $2::uuid)
ORDER BY scope, is_system DESC, code
`

type ListRolesParams struct {
	Scope          *string
	OrganizationID uuid.NullUUID
}

// Todos los roles, con filtros opcionales (consola de la plataforma).
func (q *Queries) ListRoles(ctx context.Context, arg ListRolesParams) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles, arg.Scope, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Scope,
			&i.OrganizationID,
			&i.IsSystem,
			&i.OrgAssignable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesForOrganization = `-- name: ListRolesForOrganization :many
SELECT id, code, name, description, scope, organization_id, is_system, org_assignable, created_at, updated_at FROM roles
WHERE scope = 'organization' AND (organization_id IS NULL OR organization_id = $1)
ORDER BY is_system DESC, code
`

// Los roles que se pueden dar en una organización: los de sistema de alcance
// organización más los personalizados de esa organización.
func (q *Queries) ListRolesForOrganization(ctx context.Context, organizationID uuid.NullUUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRolesForOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Scope,
			&i.OrganizationID,
			&i.IsSystem,
			&i.OrgAssignable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMembershipAccess = `-- name: ListUserMembershipAccess :many
SELECT uo.organization_id, r.id AS role_id, r.code AS role_code, r.name AS role_name,
       COALESCE(array_agg(rp.permission_code ORDER BY rp.permission_code)
                FILTER (WHERE rp.permission_code IS NOT NULL), '{}')::text[] AS permissions
FROM user_organizations uo
JOIN roles r ON r.id = uo.role_id
LEFT JOIN role_permissions rp ON rp.role_id = r.id
WHERE uo.user_id = $1
GROUP BY uo.organization_id, r.id, r.code, r.name
`

type ListUserMembershipAccessRow struct {
	OrganizationID uuid.UUID
	RoleID         uuid.UUID
	RoleCode       string
	RoleName       string
	Permissions    []string
}

func (q *Queries) ListUserMembershipAccess(ctx context.Context, userID uuid.UUID) ([]ListUserMembershipAccessRow, error) {
	rows, err := q.db.Query(ctx, listUserMembershipAccess, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserMembershipAccessRow{}
	for rows.Next() {
		var i ListUserMembershipAccessRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.RoleID,
			&i.RoleCode,
			&i.RoleName,
			&i.Permissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPlatformPermissions = `-- name: ListUserPlatformPermissions :many

SELECT DISTINCT rp.permission_code
FROM user_platform_roles upr
JOIN role_permissions rp ON rp.role_id = upr.role_id
WHERE upr.user_id = $1
`

// ---------------------------------------------------------------------------
// Acceso efectivo de un usuario (lo carga identity en cada petición)
// ---------------------------------------------------------------------------
func (q *Queries) ListUserPlatformPermissions(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserPlatformPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission_code string
		if err := rows.Scan(&permission_code); err != nil {
			return nil, err
		}
		items = append(items, permission_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPlatformRoles = `-- name: ListUserPlatformRoles :many

SELECT r.id AS role_id, r.code AS role_code, r.name AS role_name
FROM user_platform_roles upr
JOIN roles r ON r.id = upr.role_id
WHERE upr.user_id = $1
ORDER BY r.code
`

type ListUserPlatformRolesRow struct {
	RoleID   uuid.UUID
	RoleCode string
	RoleName string
}

// ---------------------------------------------------------------------------
// Roles de plataforma de un usuario
// ---------------------------------------------------------------------------
func (q *Queries) ListUserPlatformRoles(ctx context.Context, userID uuid.UUID) ([]ListUserPlatformRolesRow, error) {
	rows, err := q.db.Query(ctx, listUserPlatformRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserPlatformRolesRow{}
	for rows.Next() {
		var i ListUserPlatformRolesRow
		if err := rows.Scan(&i.RoleID, &i.RoleCode, &i.RoleName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSuperadmins = `-- name: LockSuperadmins :exec
SELECT pg_advisory_xact_lock(7101001)
`

// Serializa los cambios que pueden dejar la plataforma sin superadmin: dos
// operaciones simultáneas que cada una "deja a uno" dejarían a cero.
func (q *Queries) LockSuperadmins(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockSuperadmins)
	return err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET name = COALESCE($1, name),
    description = COALESCE($2, description),
    org_assignable = COALESCE($3, org_assignable),
    updated_at = now()
WHERE id = $4 AND NOT is_system
RETURNING id, code, name, description, scope, organization_id, is_system, org_assignable, created_at, updated_at
`

type UpdateRoleParams struct {
	Name          *string
	Description   *string
	OrgAssignable *bool
	ID            uuid.UUID
}

// Solo los personalizados: los de sistema son inmutables.
func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.Name,
		arg.Description,
		arg.OrgAssignable,
		arg.ID,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.OrganizationID,
		&i.IsSystem,
		&i.OrgAssignable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
