// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getOrganizationSettings = `-- name: GetOrganizationSettings :one
SELECT organization_id, legal_name, tax_id, contact_email, contact_phone, address, city, logo_url, timezone, locale, currency, business_hours, created_at, updated_at FROM organization_settings WHERE organization_id = $1
`

func (q *Queries) GetOrganizationSettings(ctx context.Context, organizationID uuid.UUID) (OrganizationSetting, error) {
	row := q.db.QueryRow(ctx, getOrganizationSettings, organizationID)
	var i OrganizationSetting
	err := row.Scan(
		&i.OrganizationID,
		&i.LegalName,
		&i.TaxID,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.City,
		&i.LogoUrl,
		&i.Timezone,
		&i.Locale,
		&i.Currency,
		&i.BusinessHours,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationSettingsForUpdate = `-- name: GetOrganizationSettingsForUpdate :one
SELECT organization_id, legal_name, tax_id, contact_email, contact_phone, address, city, logo_url, timezone, locale, currency, business_hours, created_at, updated_at FROM organization_settings WHERE organization_id = $1 FOR UPDATE
`

func (q *Queries) GetOrganizationSettingsForUpdate(ctx context.Context, organizationID uuid.UUID) (OrganizationSetting, error) {
	row := q.db.QueryRow(ctx, getOrganizationSettingsForUpdate, organizationID)
	var i OrganizationSetting
	err := row.Scan(
		&i.OrganizationID,
		&i.LegalName,
		&i.TaxID,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.City,
		&i.LogoUrl,
		&i.Timezone,
		&i.Locale,
		&i.Currency,
		&i.BusinessHours,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrganizationSettings = `-- name: InsertOrganizationSettings :one
INSERT INTO organization_settings (organization_id) VALUES ($1)
ON CONFLICT (organization_id) DO UPDATE SET organization_id = EXCLUDED.organization_id
RETURNING organization_id, legal_name, tax_id, contact_email, contact_phone, address, city, logo_url, timezone, locale, currency, business_hours, created_at, updated_at
`

func (q *Queries) InsertOrganizationSettings(ctx context.Context, organizationID uuid.UUID) (OrganizationSetting, error) {
	row := q.db.QueryRow(ctx, insertOrganizationSettings, organizationID)
	var i OrganizationSetting
	err := row.Scan(
		&i.OrganizationID,
		&i.LegalName,
		&i.TaxID,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.City,
		&i.LogoUrl,
		&i.Timezone,
		&i.Locale,
		&i.Currency,
		&i.BusinessHours,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizationSettings = `-- name: UpdateOrganizationSettings :one
UPDATE organization_settings
SET legal_name = $1, tax_id = $2, contact_email = $3,
    contact_phone = $4, address = $5, city = $6, logo_url = $7,
    timezone = $8, locale = $9, currency = $10,
    business_hours = $11, updated_at = now()
WHERE organization_id = $12
RETURNING organization_id, legal_name, tax_id, contact_email, contact_phone, address, city, logo_url, timezone, locale, currency, business_hours, created_at, updated_at
`

type UpdateOrganizationSettingsParams struct {
	LegalName      *string
	TaxID          *string
	ContactEmail   *string
	ContactPhone   *string
	Address        *string
	City           *string
	LogoUrl        *string
	Timezone       string
	Locale         string
	Currency       string
	BusinessHours  []byte
	OrganizationID uuid.UUID
}

// El servicio fusiona el cambio parcial con la fila leída y escribe la fila completa.
func (q *Queries) UpdateOrganizationSettings(ctx context.Context, arg UpdateOrganizationSettingsParams) (OrganizationSetting, error) {
	row := q.db.QueryRow(ctx, updateOrganizationSettings,
		arg.LegalName,
		arg.TaxID,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.Address,
		arg.City,
		arg.LogoUrl,
		arg.Timezone,
		arg.Locale,
		arg.Currency,
		arg.BusinessHours,
		arg.OrganizationID,
	)
	var i OrganizationSetting
	err := row.Scan(
		&i.OrganizationID,
		&i.LegalName,
		&i.TaxID,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.City,
		&i.LogoUrl,
		&i.Timezone,
		&i.Locale,
		&i.Currency,
		&i.BusinessHours,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
