// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersFiltered = `-- name: CountUsersFiltered :one
SELECT count(*) FROM users u
WHERE ($1::text IS NULL
        OR u.email ILIKE '%' || $1::text || '%'
        OR u.full_name ILIKE '%' || $1::text || '%')
  AND ($2::boolean IS NULL OR u.is_active = $2::boolean)
  AND ($3::text IS NULL
        OR EXISTS (SELECT 1 FROM user_platform_roles upr JOIN roles r ON r.id = upr.role_id
                   WHERE upr.user_id = u.id AND r.code = $3::text)
        OR EXISTS (SELECT 1 FROM user_organizations uo JOIN roles r ON r.id = uo.role_id
                   WHERE uo.user_id = u.id AND r.code = $3::text))
  AND ($4::uuid IS NULL
        OR EXISTS (SELECT 1 FROM user_organizations uo
                   WHERE uo.user_id = u.id AND uo.organization_id = $4::uuid))
`

type CountUsersFilteredParams struct {
	Search         *string
	IsActive       *bool
	Role           *string
	OrganizationID uuid.NullUUID
}

func (q *Queries) CountUsersFiltered(ctx context.Context, arg CountUsersFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersFiltered,
		arg.Search,
		arg.IsActive,
		arg.Role,
		arg.OrganizationID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, full_name, is_active, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, full_name, is_active, created_at, updated_at FROM users WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (id, email, full_name, is_active, created_at, updated_at)
VALUES ($1, $2, $3, TRUE, timezone('utc', now()), timezone('utc', now()))
RETURNING id, email, full_name, is_active, created_at, updated_at
`

type InsertUserParams struct {
	ID       uuid.UUID
	Email    string
	FullName *string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.ID, arg.Email, arg.FullName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembershipsByUser = `-- name: ListMembershipsByUser :many
SELECT uo.organization_id, o.name AS organization_name, o.slug AS organization_slug,
       o.status AS organization_status, o.plan_tier AS plan_tier,
       r.id AS role_id, r.code AS role_code, r.name AS role_name
FROM user_organizations uo
JOIN organizations o ON o.id = uo.organization_id
JOIN roles r ON r.id = uo.role_id
WHERE uo.user_id = $1
ORDER BY o.name
`

type ListMembershipsByUserRow struct {
	OrganizationID     uuid.UUID
	OrganizationName   string
	OrganizationSlug   string
	OrganizationStatus string
	PlanTier           string
	RoleID             uuid.UUID
	RoleCode           string
	RoleName           string
}

func (q *Queries) ListMembershipsByUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsByUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsByUserRow{}
	for rows.Next() {
		var i ListMembershipsByUserRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.OrganizationName,
			&i.OrganizationSlug,
			&i.OrganizationStatus,
			&i.PlanTier,
			&i.RoleID,
			&i.RoleCode,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByUsers = `-- name: ListMembershipsByUsers :many
SELECT uo.user_id, uo.organization_id, o.name AS organization_name, o.slug AS organization_slug,
       r.id AS role_id, r.code AS role_code, r.name AS role_name
FROM user_organizations uo
JOIN organizations o ON o.id = uo.organization_id
JOIN roles r ON r.id = uo.role_id
WHERE uo.user_id = ANY($1::uuid[])
ORDER BY uo.user_id, o.name
`

type ListMembershipsByUsersRow struct {
	UserID           uuid.UUID
	OrganizationID   uuid.UUID
	OrganizationName string
	OrganizationSlug string
	RoleID           uuid.UUID
	RoleCode         string
	RoleName         string
}

func (q *Queries) ListMembershipsByUsers(ctx context.Context, userIds []uuid.UUID) ([]ListMembershipsByUsersRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUsers, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsByUsersRow{}
	for rows.Next() {
		var i ListMembershipsByUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.OrganizationSlug,
			&i.RoleID,
			&i.RoleCode,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.email, u.full_name, u.is_active, u.created_at, u.updated_at FROM users u
WHERE ($1::text IS NULL
        OR u.email ILIKE '%' || $1::text || '%'
        OR u.full_name ILIKE '%' || $1::text || '%')
  AND ($2::boolean IS NULL OR u.is_active = $2::boolean)
  AND ($3::text IS NULL
        OR EXISTS (SELECT 1 FROM user_platform_roles upr JOIN roles r ON r.id = upr.role_id
                   WHERE upr.user_id = u.id AND r.code = $3::text)
        OR EXISTS (SELECT 1 FROM user_organizations uo JOIN roles r ON r.id = uo.role_id
                   WHERE uo.user_id = u.id AND r.code = $3::text))
  AND ($4::uuid IS NULL
        OR EXISTS (SELECT 1 FROM user_organizations uo
                   WHERE uo.user_id = u.id AND uo.organization_id = $4::uuid))
ORDER BY u.email, u.id
LIMIT $6 OFFSET $5
`

type ListUsersParams struct {
	Search         *string
	IsActive       *bool
	Role           *string
	OrganizationID uuid.NullUUID
	PageOffset     int32
	PageSize       int32
}

// Filtros del listado de la plataforma. `search` ya viene escapado para LIKE.
// `role` casa con el código de un rol de plataforma o de organización;
// `organization_id`, con pertenecer a esa organización.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Search,
		arg.IsActive,
		arg.Role,
		arg.OrganizationID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActive = `-- name: SetUserActive :one
UPDATE users
SET is_active = $1, updated_at = timezone('utc', now())
WHERE id = $2
RETURNING id, email, full_name, is_active, created_at, updated_at
`

type SetUserActiveParams struct {
	IsActive bool
	ID       uuid.UUID
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserActive, arg.IsActive, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserFullName = `-- name: UpdateUserFullName :one
UPDATE users
SET full_name = COALESCE($1, full_name),
    updated_at = timezone('utc', now())
WHERE id = $2
RETURNING id, email, full_name, is_active, created_at, updated_at
`

type UpdateUserFullNameParams struct {
	FullName *string
	ID       uuid.UUID
}

func (q *Queries) UpdateUserFullName(ctx context.Context, arg UpdateUserFullNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserFullName, arg.FullName, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userEmailExists = `-- name: UserEmailExists :one
SELECT EXISTS (SELECT 1 FROM users WHERE lower(email) = lower($1))
`

// Sin distinguir mayúsculas: hay correos históricos guardados como se escribieron,
// y el índice único sí las distingue.
func (q *Queries) UserEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, userEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
